### PR TITLE
Merge develop branches

### PR DESCRIPTION
**Pull request by monkey0506**
I'll be tackling the task of merging develop-3.3.5 into develop-3.4.0. If I understand @ivan-mogilko correctly then 805017d is the first actual commit in the merging process, and includes changed files that did not produce any conflicts in merging.

The next step will be to add trivially conflicting files, such as cases where header files have been included/removed, or something has simply been renamed. This will be merged as a single commit.

Finally, individual features from the remaining conflicting files will be reimplemented.

If I've misunderstood anything, let me know.

### CODE REVIEW

**Comment by monkey0506** [comment]
Changes not staged for commit (conflicts):

	modified:   Common/core/def_version.h
	modified:   Common/gfx/allegrobitmap.h
	modified:   Common/gfx/bitmap.cpp
	modified:   Common/gfx/bitmap.h
	modified:   Common/util/geometry.h
	modified:   Common/util/memory.h
	modified:   Common/util/string.h
	modified:   Compiler/script/cc_compiledscript.cpp
	modified:   Compiler/script/cc_symboldef.h
	modified:   Compiler/script/cc_symboltable.cpp
	modified:   Compiler/script/cc_symboltable.h
	modified:   Compiler/script/cs_compiler.cpp
	modified:   Compiler/script/cs_parser.cpp
	modified:   Compiler/script/cs_parser_common.h
	modified:   Compiler/test/cc_symboltable_test.cpp
	modified:   Editor/AGS.Controls/ScintillaNET/ScintillaControl.cs
	modified:   Editor/AGS.Editor/Panes/ScriptEditor.cs
	modified:   Editor/AGS.Editor/Panes/SpriteSelector.cs
	modified:   Editor/AGS.Editor/Tasks.cs
	modified:   Editor/AGS.Types/Properties/AssemblyInfo.cs
	modified:   Engine/ac/display.cpp
	modified:   Engine/ac/display.h
	modified:   Engine/ac/game.cpp
	modified:   Engine/ac/gamesetup.cpp
	modified:   Engine/ac/gamesetup.h
	modified:   Engine/ac/global_display.cpp
	modified:   Engine/ac/global_game.cpp
	modified:   Engine/ac/global_screen.cpp
	modified:   Engine/ac/room.cpp
	modified:   Engine/device/mousew32.cpp
	modified:   Engine/font/fonts_engine.cpp
	modified:   Engine/main/config.cpp
	modified:   Engine/main/config.h
	modified:   Engine/main/engine.cpp
	modified:   Engine/main/graphics_mode.cpp
	modified:   Engine/main/graphics_mode.h
	modified:   Engine/platform/base/agsplatformdriver.h
	modified:   Engine/platform/linux/acpllnx.cpp
	modified:   Engine/platform/windows/acplwin.cpp
	modified:   Engine/platform/windows/gfx/ali3dd3d.cpp
	modified:   Engine/resource/resource.h
	modified:   Engine/resource/version.rc
	modified:   Engine/script/systemimports.cpp
	modified:   Engine/test/test_all.cpp
	modified:   README.md
	modified:   Solutions/Common.Lib/Common.Lib.vcproj
	modified:   Solutions/Compiler.Lib/Compiler.Lib.Test.vcproj
	modified:   Solutions/Engine.App/Engine.App.vcproj
	modified:   debian/changelog

Untracked files:

	Engine/setup/                   (deleted by us)
	Engine/test/test_file.h         (deleted by us)
	Engine/test/test_string.h       (deleted by us)

**Comment by ivan-mogilko** [comment]
Thank you.
Could you try making a list of commits in dev-3.3.5 thread that cause these conflicts?

**Comment by ivan-mogilko** [comment]
@monkey0506 , I am not aware of your progress here (is there any?); but I was revisiting this merge and thought that this path we chose could be a wrong one.

The conflicting changes between two branches span over 6+ months, and made by several contributors. Unfortunately, when you create a merge commit, ignoring conflicting changes, git won't assist you in further work, and you will have to remember everything you skipped and track code copy progress yourself. This way is error prone, and even more so when the changes were done by several people.

I believe that we will have to consult commit authors along the way, or even let them solve the conflicts in their code.

That is why I propose go different way. Instead of straight merging the head of the develop-3.3.5 branch into 3.4.0, we could "split" the develop-3.3.5 branch in chunks (containing related commits, or bunches of unrelated but minor changes) and merge it chunk by chunk.

Advantages of such methods:
* we will be dealing with limited number of changes and conflicts each step, it will be easier to track what we do;
* it will be clear which commits we are dealing with and who are their authors (so we may discuss the conflicts with them or pass the task of merging the chunk to them).

Disadvantages:
* since some later commits are fixes to previous ones, the original code and fixed code may go into separate merges. This means that there be some extra code changes recorded in history, and in some cases it will take additional effort to resolve conflicts in same files again.

**Comment by sonneveld** [comment]
Could another way be to merge 3.3.5 into master and then rebase 3.4.0 on top of master?  I do like the breaking up the work into chunks idea though.

**Comment by ivan-mogilko** [comment]
@sonneveld 
>Could another way be to merge 3.3.5 into master and then rebase 3.4.0 on top of master?

It will take far more effort to do so. These branches were developed in parallel for more than 1.5 years, and the 3.4.0 has master merged into itself several times (after every 3.3.* update release).

Since rebasing does copy branch commits starting from the very first one, we practically will have to resolve same conflicts that were resolved year ago over and over again.

PS. I first edited Nick's comment by mistake... then restored to most extent.

**Comment by ivan-mogilko** [comment]
The merge is going to be done in a different way.

**Pull request closed without merging**
