### PR TITLE
Script API: helper functions for Viewport and Camera

### PR DESCRIPTION
**Pull request by ivan-mogilko**
This adds a bunch of script functions to work with Viewport and Camera.

But first of all, I added Screen struct to place static screen-related properties and functions there. At the moment its declaration looks like this:
<pre>
builtin struct Screen {
  /// Gets the width of the game resolution.
  import static readonly attribute int Width;
  /// Gets the height of the game resolution.
  import static readonly attribute int Height;
  /// Gets/sets whether the viewport should automatically adjust itself and camera to the new room's background size
  import static attribute bool AutoSizeViewportOnRoomLoad;
  /// Gets the primary room viewport
  import static readonly attribute Viewport *Viewport;

  /// Returns the point in room which is displayed at the given screen coordinates
  import static Point *ScreenToRoomPoint(int sx, int sy);
};
</pre>

You may notice there's now Point struct in the builtin API. It's declaration is trivial:
<pre>
managed struct Point {
	int x, y;
};
</pre>
So far this is the only managed struct that is intentionally not declared as "builtin", because I thought it would be good to let users also spawn its instances in script.

* Moved RoomViewport and AutoSizeViewportOnRoomLoad properties from Game to Screen struct.
* Deprecated System.ScreenWidth and System.ScreenHeight, as well as System.ViewportWidth and System.ViewportHeight in favor of Screen.Width/Height.

Added following to the Viewport:
<pre>
  /// Returns the viewport at the specified screen location.
  import static Viewport *GetAtScreenXY(int x, int y);
  /// Changes viewport's position on the screen
  import void SetPosition(int x, int y, int width, int height);
  /// Returns the point in room corresponding to the given screen coordinates if seen through this viewport.
  import Point *ScreenToRoomPoint(int scrx, int scry, bool clipViewport = true);
  /// Returns the point on screen corresponding to the given room coordinates if seen through this viewport.
  import Point *RoomToScreenPoint(int roomx, int roomy, bool clipViewport = true);
</pre>

**Removed ScaleX and ScaleY from Camera.**

Added following to the Camera:
<pre>
  /// Changes camera position in the room and disables automatic tracking of the player character.
  import void SetAt(int x, int y);
  /// Changes camera's capture dimensions in room coordinates.
  import void SetSize(int width, int height);
</pre>

**NOTES:**
* Screen.ScreenToRoomPoint returns null if there is no room Viewport under these coordinates. If there will be multiple viewports supported in the future engine simply won't know which to choose if there's none directly there.
* Both Viewport.ScreenToRoomPoint and Viewport.RoomToScreenPoint have clipViewport parameter which tells whether they should return null if the coordinates lie outside of the visible part of the room.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
So, the recent conversation with @ericoporto on forums led me to a thought to completely remove the Scale* properties from the camera.

Initially I added these properties as means of automatic camera resize. But thinking this over, this currently lead to more problems. In AGS right now the camera's position is defined as a top-left of a rectangle, and, for example, when tracking the player character camera is placed at character's location minus half-size of camera. If the camera's size is not fixed (as when defined by autoscale) we need to put both camera and viewport into calculation. Which is frankly a hack and may cause troubles when (if) multiple viewports/cameras are supported. Even now camera's true position values become undetermined without knowing viewport. So this was something not thought through very well in the first place.

**Comment by ivan-mogilko** [comment]
On other topic, what do you think about GetRoomLocation/GetScreenLocation function names?
I have doubts because there are other script functions with term "location": GetLocationName and GetLocationType, where "location" means some entity inside the room (object, hotspot, etc).
What could be alternate good variants for functions that convert coordinates?

**Comment by ericoporto** [comment]
If we consider the Room as our game world, we have a RoomPoint, and a ScreenPoint, where transforming from RoomPoint implies knowing the X,Y RoomPoint, the Camera, and the Viewport to findout the x,y ScreenPoint. I think the X and Y case has similar meaning in AGS too.

**Comment by ivan-mogilko** [comment]
Maybe ScreenToRoomPoint/RoomToScreenPoint, without "From"? Just trying to shorten them a bit :).

**Comment by ericoporto** [comment]
Yeah, that works! One could also use coordinates, but point is shorter!

**Pull request merged**
