### PR TITLE
Improve argument print in DumpInstruction

### PR DESCRIPTION
**Pull request by criezy**
To help me debug some issues in ScummVM, I made improvements to the DumpInstruction functions.
I am not sure all the changes are a good idea, so I made them incrementally in three separate commits (so that for example you may decide to merge only the first commit).

Feedback and suggestions, if you think I made some mistakes or something could be improved, are welcome.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
We very rarely use this today, so it's not critical if it does something different.

By the way, were you familiar with agsutils tools that write script disassembly?
https://github.com/rofl0r/agsutils/

**Comment by criezy** [comment]
> By the way, were you familiar with agsutils tools that write script disassembly?
> https://github.com/rofl0r/agsutils/

I am yes. But for some reason `agscriptxtract` errors out with the game I was trying to debug.

**Comment by rofl0r** [comment]
> But for some reason agscriptxtract errors out with the game I was trying to debug.

could you point me to that game ? i'd like to fix this.

**Comment by criezy** [comment]
> > But for some reason agscriptxtract errors out with the game I was trying to debug.
> 
> could you point me to that game ? i'd like to fix this.

Sure. The game is AGDI's Quest for Glory II.
`agscriptxtract` is asserting here:
```gdb
    frame #4: agscriptxtract`ADF_read_custom_property(a) at DataFile.c:462:2
   459 	
   460 	int ADF_read_custom_property(ADF *a) {
   461 		unsigned i, x, propver = AF_read_uint(a->f);
-> 462 		assert(propver <= 2);
   463 		x = AF_read_uint(a->f); /* numprops */
   464 		for(i=0;i<x;++i) {
   465 			if(propver == 1) {
Target 0: (agscriptxtract) stopped.
(lldb) p propver
(unsigned int) $0 = 1734828356
```

With this call stack:
```gdb
  * frame #4: agscriptxtract`ADF_read_custom_property(a) at DataFile.c:462:2
    frame #5: agscriptxtract`ADF_open(a, filename="../temp//game28.dta") at DataFile.c:667:8
    frame #6: agscriptxtract`main(argc, argv) at agscriptxtract.c:201:6
```

**Comment by rofl0r** [comment]
thanks, fixed in https://github.com/rofl0r/agsutils/commit/e98fab2af8136642c5dfd41d56bf5e95b66133f1

**Pull request merged**
