### PR TITLE
EditorConfig is awesome: http://EditorConfig.org

### PR DESCRIPTION
**Pull request by persn**
EditorConfig is the new trendy and hip config file that is reusable across various IDEs and text editors (check their homepage for a list)

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
> new trendy and hip config file
this pull request looks like its a spambot's doing :/

**Comment by persn** [comment]
Yes, sorry I was being funny

**Comment by ivan-mogilko** [comment]
Oh ok, :) that was a little different from usual.

**Comment by ivan-mogilko** [comment]
I have two questions:
1. This won't automatically modify existing code's style, only the new one which you type?
2. Not sure how well the line ending definition will work; for example right now my git repository is configured with autocrlf = true (checkout Windows endings / commit Unix endings), won't there be conflicts with that? Perhaps leave line endings out and let git do them instead?

**Comment by persn** [comment]
> This won't automatically modify existing code's style, only apply to the new one which you type?

Yes.

> Not sure how well the line ending definition will work; for example right now my git repository is configured with autocrlf = true (checkout Windows endings / commit Unix endings), won't there be conflicts with that? Perhaps leave line endings out and let git do them instead?

I haven't noticed any issues with this previously and I've been using editorconfig for a couple of years now. My git is set up the same as yours, I work in projects where developers are using Windows, Linux and Mac.

**Pull request merged**
