### PR TITLE
Add project specification document

### PR DESCRIPTION
**Pull request by morganwillcock**
I've been working for a while try to create a document to establish direction of the project and try to gather my thoughts regarding how I feel AGS should be updated. After much note-taking and rewriting I came to realise that by following by own logic it was impossible to make any meaningful and valid decision without first establishing what AGS is meant to do. In fact, my only goal here is to close a single issue (#769).

Within the document I've started the issues which I feel are relevant to make a decision, but also I have purposefully omitted any sort of conclusion before submitting this as a change request.

I would like to request feedback on any missing relevant information or errors, to get the document to the point that it is deemed a good representation of the current situation. Perhaps after some time has elapsed (maybe 3-4 weeks?) active committers will agree to merge the document to record a decision, and then the project goal will be set.

Note: the document may contain diagrams so a CI task is configured to export everything to HTML

### CODE REVIEW

**Comment by AlanDrake** [comment]
I stand by my former decisions:
AGS primary goal is to make games
The current incarnation, which deviated from the original goals, can keep existing in the AGS3 branch with appropriate bugfixes and support but no new fetures.

**Comment by morganwillcock** [comment]
Yes. I think I would agree that it has accidentally deviated from its original course, so I am interested to hear from anyone with a counter argument or different view.

**Comment by morganwillcock** [comment]
I was expecting that someone would challenge the position, but it has been two months. No-one has directly argued the opposite and the [forum poll](https://www.adventuregamestudio.co.uk/forums/index.php?topic=57990.0) shows minimal objections (as well as numerous people questioning why this is even an issue).

So I think I suggest to close this PR, submit a new PR to the main readme file which states the purpose, without being too specific but making it clear that this is a game development tool, and then this closes #769.

**Comment by ericoporto** [comment]
Agreed. Let's move forward! :D

**Pull request closed without merging**
