### PR TITLE
Theme support for Log Panel

### PR DESCRIPTION
**Pull request by AlanDrake**
This PR adds theme support to the log panel and fixes a couple things:
- added default margins to the RichTextBox
- resized log panel buttons to match icon size

Was there anything new that was missing theming?

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
> Was there anything new that was missing theming?

Looks like the LogPanel's Settings pane is not themed. You make it visible by pressing "Show Settings" toolbar button.

**Comment by AlanDrake** [comment]
It's the propertyGrid (already themed), but I noticed I should also ltheme the splitter bar.

**Comment by ivan-mogilko** [comment]
> It's the propertyGrid (already themed)

For some reason "[C] VisualStudioDark" theme does not apply colors to the LogPanel's property grid. Some other themes do apply though. Do you know what may be the difference?

**Comment by AlanDrake** [comment]
> Do you know what may be the difference?

Not all compat themes have global definitions, but I just finished updating themes, so it shouldn't be a problem.

**Comment by ivan-mogilko** [comment]
Recent themes seem to fix this.

**Pull request merged**
