### PR TITLE
Refactor GUI Control classes

### PR DESCRIPTION
**Pull request by ivan-mogilko**
I am awfully sorry for doing this (sort of), but it was too hard to "let it go" when you have an almost ready piece of work that took you many days to do. So, I decided to recreate the (almost 2 years old) branch which refactors GUI Control classes.

Luckily, there were only several conflicts to resolve (the related code did not change much since the old branch was first made), and I found and fixed only couple of minor mistakes so far.

As this is refactoring, the new code is supposed to be functionally similar to an old one. Classes are tidied, and brought to general code style; some optimization is done along the way.

Notable addition is an introduction of generic FrameAlignment flags which substitute varied alignment types in Buttons, Labels and ListBox.

The code in this branch was written with the idea to keep compatibility in all known ways; but I guess it won't be hard to remove if wanted. (Adjustments to how Editor saves GUI would be required too in such case)

### CODE REVIEW

**Comment by AlanDrake** [comment]
Nice, I'll give it a pull.

**Comment by AlanDrake** [comment]
Looks good to me.

**Comment by AlanDrake** [comment]
Sorry, I found something amiss. If you try to reset the game, you get a "Error: Error: Too many control events, need newer version"
Saving loading normally does not reproduce the error, only RestartGame()

**Comment by ivan-mogilko** [comment]
That's GUIButton::Read/Write using non-matching methods to seralize text. I need to double check them and also other controls for same problem.

**Comment by AlanDrake** [comment]
Yeah, just got around to fix it.
It was the Text and the missing reserved in32 on guibutton.cpp
```
    Text.WriteCount(out, GUIBUTTON_TEXTLENGTH);
    out->WriteInt32(TextAlignment);
    out->WriteInt32(0);
```

**Comment by ivan-mogilko** [comment]
There's couple of more mistakes I found, I will be fixing them.

**Comment by ivan-mogilko** [comment]
Hmm.. btw I have a strike of deja vu while fixing these bugs. Probably I've already tried to ressurect this branch before but did not finish for some reason.

**Comment by ivan-mogilko** [comment]
Updated:
* Fixed button serialization
* Fixed list box serialization when savedgames are filled into it.
* Fixed graphic buttons with unremoved "New Button" text still displaying it in some cases (AGS has a compatibility requirement that this text is not displayed for graphic buttons).
* Corrected code style for non-public member variables.

Also, I realized that we cannot change alignment properties right away without also changing them in Editor, and hence modifying data format. So I made the conversion into generic type to be performed at the moment of drawing, and added TODO notes in engine and editor, suggesting moving to universal text alignment type for all GUI controls.

**Pull request merged**
