### PR TITLE
Fixes float locale dependant in #1015

### PR DESCRIPTION
**Pull request by ericoporto**
need to not use `LC_ALL`on MacOS

### CODE REVIEW

**Comment by AlanDrake** [comment]
So it causes probems on MacOS? What about just `LC_NUMERIC` instead of `LC_ALL`?

**Comment by ericoporto** [comment]
I added the ifdef for it just for Linux since this wasn't reported in other platforms.

**Comment by ivan-mogilko** [comment]
Sorry for the delay.

My only concern is the place where you put this; `start_game` function may be called more than once and is related to start running with already loaded data and configured options.
Also, it's best to avoid placing system #ifdefs in the game logic code.

Would it still work if placed in `ags_entry_point` function? There's already some system-specific code that looks like this:
`#if AGS_PLATFORM_OS_WINDOWS
    setup_malloc_handling();
#endif`

**Comment by ericoporto** [comment]
Hey, I to tried the suggestion here, but for reasons I don't understand it doesn't work with `ags_entry_point`. I placed right after the mentioned `#if AGS_PLATFORM_OS_WINDOWS`.

**Comment by ericoporto** [comment]
Found where the locale is being changed!!! It's in the `install_keyboard();` line on `void engine_init_keyboard()` in `Engine/main/engine.cpp`. I can't trace the error more than this, I think it's somewhere in allegro from this [forum messa here](). I can switch to use `LC_NUMERIC` and do it like this:

```cpp
void engine_init_keyboard()
{
#ifdef ALLEGRO_KEYBOARD_HANDLER
    Debug::Printf(kDbgMsg_Init, "Initializing keyboard");

    install_keyboard();
#endif
#if AGS_PLATFORM_OS_LINUX
    setlocale(LC_NUMERIC, "C");
#endif
}
```

**Comment by ivan-mogilko** [comment]
This makes sense: first initialize library, then adjust settings.

Also, apparently xkeyboard.c is the only place where Allegro calls `setlocale`, which explains why no other port has this issue.

**Comment by ivan-mogilko** [comment]
Actually, I think this may be cherry picked to release-3.5.0 too, since it's a simple fix to an obvious bug.

**Comment by ericoporto** [comment]
Cool! I can finally run my ags tests without it failing in my PC because my float conversion checks xD

**Pull request merged**
