### PR TITLE
Add stdio.h includes

### PR DESCRIPTION
**Pull request by ffaf1**
As requested in #1434

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
@ffaf1 Thank you,

btw I thought you name sounds familiar, and found you already authored a small commit many years ago (2653c97572a3649701ddc97ac3c98672e1ba87fe), and even mentioned in our Credits :).

**Comment by ericoporto** [comment]
I just found this patch in the wild : https://github.com/OpenMandrivaAssociation/ags/blob/master/ags-3.5.0.24-compile.patch

Maybe this commit need to be ported to the 3.5.1 release branch.

**Comment by ivan-mogilko** [comment]
3.5.1 and 3.6.0 may already have some differences in how code is organized, it's best to test 3.5.1 separately with the same compiler to be sure.

**Comment by rofl0r** [comment]
> Also interesting note here: https://github.com/OpenMandrivaAssociation/ags/blob/f9626b54751394b0c52142e8c0e8407c2c5ddf78/ags.spec#L44

> # Force clang -- gcc 6.x miscompiles ags

i'm building ags with gcc 6.5.0 since years - no issues encountered

**Pull request merged**
