### PR TITLE
IniFile class and reading game config from the generic key-value map

### PR DESCRIPTION
**Pull request by ivan-mogilko**
Few planned future updates requires writing certain options back to config file on exit.
Unfortunately, config write functions provided by Allegro 4 library proved to not be fully reliable: they fail if the config file format is slightly different from their expectations; besides there is a chance we will be moving away from Allegro 4 in the future.

This pull request introduces IniFile class that constructs a description of INI either by parsing a file or by user command, allows to iterate sections and items, and write the contents back into file. IniFile supports merging changes into existing file; this is implemented by remembering precise locations of items in the text. If a single existing item value was changed by user, it is replaced while keeping the rest of the contents unchanged.

Also provided utility functions which exchange data between IniFile and a key-value tree (a map of maps of strings) in both directions. The named tree is then used during actual game setup routine.
The advantage of separating the configuration tree from IniFile is that the config tree may be easily filled from other sources as well, for example - from command line arguments.

Advanced changes that would follow this request:
* Saving necessary config options back to the config file on game exit;
* Combining options from multiple sources (general config, platform-specific config, command line parameters) into the single configuration map.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
On a side note, I would need to recreate engine tests as a separate automatic test project, as was done for Compiler library. I guess I will do so a bit later, as another pull request.

**Comment by sonneveld** [comment]
How does combining settings from multiple sources work with saving back to ini files?

**Comment by ivan-mogilko** [comment]
@sonneveld 
> How does combining settings from multiple sources work with saving back to ini files?

Combining options from sources is done with the use of ConfigTree, which is simply a two-level map (map of string maps). It does not really matter how this map is filled.
IniUtil::Write and IniUtil::Merge functions simply save the resulting tree in INI format; the latter function uses IniFile class as a medium, which helps substituting new values into existing file without clearing existing content.

**Comment by ivan-mogilko** [comment]
Android and PSP ports compiling now (they were using some of the functions I rewrote).
May someone test that they actually work? I cannot do this right now myself.

On a side-note, before someone asks why there is a code duplication between these ports, we already have a related ticket: https://github.com/adventuregamestudio/ags/issues/104

**Comment by ivan-mogilko** [comment]
It seems I need to add new cpp references into iOS project. How do I do that?

**Comment by sonneveld** [comment]
Try this patch!

[ini-xcode.patch.txt](https://github.com/adventuregamestudio/ags/files/20169/ini-xcode.patch.txt)

**Comment by ivan-mogilko** [comment]
@sonneveld 
I cannot apply this patch, the project.pbxproj contents does not match... did you based this patch from another branch?

**Comment by ivan-mogilko** [comment]
Okay, I got it, I squashed fixes and rebased whole pull request on top of recent dev-3.3.5.

**Pull request merged**
