### PR TITLE
Editor: DialogEditor selects line when required

### PR DESCRIPTION
**Pull request by ericoporto**
fixes what was reported by Dave here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59842.msg636646209#msg636646209

I noticed this was different in Script Editor: https://github.com/adventuregamestudio/ags/blob/874fbbc7a729866dd8fa85c0cf1b0e2c75fce25c/Editor/AGS.Editor/Panes/ScriptEditor.cs#L515-L518

but also, it wasn't respecting what was asked in the `ZoomToFileEventArgs`, since `SelectLine` was true.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
Had you chance to look into the window not scrolling to the selected position? I've been trying to reproduce that, and it happens sometimes. I'm not yet fully certain, but it seems this happens only the first time the dialog editor is opened by clicking on found item.

**Comment by ericoporto** [comment]
Ended up using the Paint event to make sure the layout was already adjusted. I ended up using it through an elimination process, since other events I tried failed. Since the code is self contained there, I think it should be fine.

**Comment by ivan-mogilko** [comment]
The latest commit seem to fix the reported problem, but it broke the "Find next" command in the dialog script: now it does not scroll the window nor highlights the text.

**Comment by ericoporto** [comment]
ok, I switched so I only delay the find in the next paint event if the dialog editor is not yet shown on screen. This appears to fix the find next issue.

**Pull request merged**
