### PR TITLE
When user interface is disabled, only grey/black out GUI buttons that have an associated click action.

### PR DESCRIPTION
**Pull request by fernewelten**
Buttons that don't have any click action are, in effect, just labels. The user can't react to them in the first place. So when the interface becomes disabled, the user should not get the message that they _now_ cannot react to them. 

This PR changes the UI so that GUI buttons whose ClickAction is NoAction are treated as labels.

(Why would an AGS coder use a button without any click action instead of a label in the first place? Because GUI labels can't show sprites. So if you want to denote with a spiffy sprite, e.g., whether Ego can currently fly or not, then a label won't do and you need a button.)

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
Do buttons with no click actions still display "pushed" graphic when clicked?

**Comment by ivan-mogilko** [comment]
> Do buttons with no click actions still display "pushed" graphic when clicked?

So, I tested this, and the putton still may be pushed even if action = No Action.

My point being, if you want to treat a button with no action as a "graphical label", this should perhaps be consistent, and it should not be pushable as well.

Regarding the code itself, a little nitpick, but could you call variable `button_is_clickable` something else, because buttons already have "Clickable" property with different meaning.

**Comment by rofl0r** [comment]
if a label with graphics is desired, why not simply add a graphical_label gui control ?

**Comment by ivan-mogilko** [comment]
> if a label with graphics is desired, why not simply add a graphical_label gui control ?

I would suggest that is better in the long term, except much more things to code in both engine and editor.

**Comment by rofl0r** [comment]
if i was to implement that, i'd just change label to support an additional graphic and add a property graphical=no (or graphics=null) to the traditional label variant, whereas the graphical variant would have set it to yes.

**Comment by ivan-mogilko** [comment]
> if i was to implement that, i'd just change label to support an additional graphic and add a property graphical=no (or graphics=null) to the traditional label variant, whereas the graphical variant would have set it to yes.

That is also an option.

Anyhow, I think the purpose of this pr is to correct already existing behavior rather than introduce a new one. Frankly I think it is even suitable for ags3, because displaying disabled state on a button with no action is wrong.

**Comment by fernewelten** [comment]
So what do you want me to implement?
- [ ] Only treat those buttons as labels that don't have any associated `PushedImage`.
- [ ] When buttons have `ClickAction` set to `NoAction` then any associated `PushedImage` is ignored. Those inoperable buttons only show their `Image`. If the user clicks onto them, they still don't show their pushed graphic. 

How do we treat `MouseoverImage`? Likewise?

**Comment by ivan-mogilko** [comment]
Actually, I am not sure about whole thing at all. What if user made a no action button for a purpose to work as a pushable button that does nothing? I don't know why, for some obscure reason. Such scenario is still valid, as button is intended to work as button.

**Comment by fernewelten** [comment]
@rofl0r 

I can well imagine touching up labels, especially in ags4. But let's keep that separate and do this one first. 

We might envision having a sound that is automatically played whenever a button is clicked, in the same way that view graphics can have a sound that is played whenever the graphic is displayed. But again, that's an idea that should be further discussed and then put into another PR.

**Comment by fernewelten** [comment]
> Actually, I am not sure about whole thing at all anymore. What if user made a no action button for a purpose to work as a pushable button that does nothing?

Then they could set `ClickAction` to `RunAction` and associate an empty event function.

**Comment by ivan-mogilko** [comment]
Actually, I am not sure about whole thing at all anymore. What if user made a no action button for a purpose to work as a pushable button that does nothing? I don't know why, for some obscure reason. Such scenario is still valid, as button is intended to work as button.

**Comment by ivan-mogilko** [comment]
> > What if user made a no action button for a purpose to work as a pushable button that does nothing?
> 
> Then they could set `ClickAction` to `RunAction` and associate an empty event function.

But this is a very obscure rule.

**Comment by ivan-mogilko** [comment]
> I can well imagine touching up labels, especially for ags4. But let's keep that separate and do this one first.

The question is then, why do this change to a button at all in ags4? Buttons were used to display sprites mostly because there was nothing else. So, if we are doing something in context of a next big version, would not it be a better choice to add that missing control type instead?

**Comment by ivan-mogilko** [comment]
Okay, sorry, I need to think a little more about this.
Maybe "No action" was originally intended for buttons that just display a graphic, and this was made for simplicity sake (to reuse same control).

**Comment by ivan-mogilko** [comment]
@fernewelten 
Alright, sorry for all the multiple comments.

I am coming to a thought that regardless of how we change the button now it will still be not fully right, because this object never had fully consistent behavior for its two main uses, and relied on careful setup by user.
Your main suggestion here is to fix one of these uses, which makes sense at least until we further redesign gui controls.

Therefore, I remove my proposal about disabling push state for such button, let user handle this the way they want. After all, if they dont want it to have any action *and* dont want button to be pushed, they may as well set Clickable false, and problem is solved.

So, if you just fix code a little according to my first comment, I will accept this PR.

**Pull request merged**
