### PR TITLE
Implemented basic functionality for --tell command (take 2, INI version)

### PR DESCRIPTION
**Pull request by ivan-mogilko**
For #520 (attempt 2)

* Engine detects command line arguments starting with `--tell-`, the suffixes are stored in a set as keys.
* If there was at least one such argument, engine will print out requested info to std out and stop. Because some of this info requires data from the game header, printing is done after game files were found and pre-read.
* Information is printed out in INI format, just like the game config, and may contain multiple sections of key/value pairs.
* This is not very common for INI, but currently the output also has "nested" sections which are indicated by '@' character(s) in their names. This is currently used to group number of sections together and give an extra leeway in avoiding possible naming conflicts in the future. The main reason for this addition was that one of the supported commands is "--tell-config" that prints all the parsed user config, which contains multiple sections on its own.

TODO and potential issues:
* **[DONE]** Engine prints some other messages to std out, such as its name and version, game location and version, maybe some warnings and errors. Should these be suppressed to simplify parsing for external process?
* **[DONE]** Need to detect early whether it is required to read game at all, because some of the info may not need that (like, if we need to print only list of supported gfx drivers);
* **[sort of]** Need to figure out good names for the keys.
* **[DONE]** Implement a minimal necessary set of info keys, as noted in #520.

Currently supported keys:
* --tell or --tell-all: prints everything;
* --tell-config: prints config (must locate game data and parse user config)
* --tell-configpath: prints paths to all 3 configs (default, global and user) and other info necessary to locate these (like game name - to find user data dirs).
* --tell-graphicdrivers: list of supported gfx drivers.

### CODE REVIEW

**Comment by ericoporto** [comment]
Screenshot_20190825-213022_bVNC Free

Pretty cool, it needs to be added to `ags --help`

**Comment by morganwillcock** [comment]
Would it be possible to get this section as `--tell-engine`:
<pre>[engine]
name = Adventure Game Studio run-time engine
version = 3.5.0.15</pre>
...instead of outputting it with every other section?

And would it be possible to remove the count key from the `--tell-graphicdrivers` output, since it means you would have to start testing the keys based on some criteria to establish whether they are keys or key metadata (test if the key is an integer and the value is a string to verify that the value is actually a graphics driver, in this case).

**Comment by ivan-mogilko** [comment]
> Would it be possible to get this section as --tell-engine:
> ...instead of outputting it with every other section?

Initially I added this because you asked for some kind of format version, so I thought having engine version may serve as a hint.

**Comment by morganwillcock** [comment]
It is good to have, but potentially you would just want this item by itself to know what else you want to query, but after that you probably don't need it again. Or you just ask for `--tell-all`.

But if you print as its own section, then I think it follows the pattern that `--tell-<section>` will print `[<section>]` or a delimited variant `[<section>@<subsection>]`.

**Comment by ivan-mogilko** [comment]
I did the changes.

**Comment by ivan-mogilko** [comment]
Come on, you can post the plain output instead of screenshots.

Yes I forgot to adjust the help this time.

**Comment by morganwillcock** [comment]
A few things I noticed, perhaps one is problematic.

<hr>

The first is just whether to make the section name and argument name plural or not. Right now there is `--tell-configpath` and `tell-graphicdrivers`, where both can return multiple values (either paths of driver names). So it is probably best to standardise on whether these arguments and sections names end in an 's' or not.

<hr>

The second is that the game name is listed under `tell-configpath`, but the game name isn't a config path. There was also some other game related information that doesn't get printed. Would it be possible to have `--tell-data` (or maybe `--tell-game` ? ) and an separate section `[data]` that is something like:

<pre>[data]
gamename = In Bloom
version = 49
compiledwith = 3.4.1.14</pre>

...or is this extra data not parsed at this point?

<hr>

Third problem, and this is probably not straightforward, on platforms that don't support the global config is it effectively disabled by using '.' as the location in the base class? On Linux you won't see any issue, as the values comes out to this:

<pre>default = /home/mwillcock/Downloads/In-Bloom/data/acsetup.cfg
global = /home/mwillcock/.local/share/ags/acsetup.cfg
user = /home/mwillcock/.local/share/ags/In Bloom/acsetup.cfg</pre>

... so given these values, it is easy to see whether these files exist or not. But if you try the same thing on macOS you get a global config path of:

<pre>global = ./acsetup.cfg</pre>

...and this is impossible to test, because where '.' is will change depending on the current working directory. So under some circumstances ./acsetup may exist, but it could be for a completely different game, or maybe it is the one in the game directory or the user one, and you mistakenly process it as the global one. It is feasible that any kind of wrapper process will be running from somewhere else, as demonstrated by the Linux launch wrapper being called the itch.io client.

I guess I don't know what to suggest to fix this, if all valid config paths are guaranteed to be absolute, perhaps it is best to omit any config paths which are relative?

**Comment by morganwillcock** [comment]
Sorry, one bit I forgot, it doesn't say the path to the game file either. So if the engine locates the path by looking inside 'data' it would be good to know which file it is using as the game.

e.g. `/home/mwillcock/Downloads/In-Bloom/data/In-Bloom.ags`

<pre>[data]
gamename = In Bloom
filename = /home/mwillcock/Downloads/In-Bloom/data/In-Bloom.ags
version = 49
compiledwith = 3.4.1.14</pre>

**Comment by ivan-mogilko** [comment]
Ammended.

**Comment by morganwillcock** [comment]
The `--help` message is out of sync again (`--tell-graphicdrivers` vs `--tell-graphicdriver`), but other than that I think everything is covered.

Regarding the macOS error code, a solution was more obvious when I actually ran the program, rather than tried to think of a solution. As well as trying to look at what went to stdin, If stderr isn't empty then there was an error. So I think that is probably good enough to tell the difference, when you know the exit code isn't going to be set.

**Pull request merged**
