### PR TITLE
develop-3.3.5--section-05 into develop-3.4.0 merge

### PR DESCRIPTION
**Pull request by sonneveld**

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
After this update the [Tween module](http://www.adventuregamestudio.co.uk/forums/index.php?topic=51820.0) cannot compile properly.

Error is:
> Tween.asc(1828): Error (line 1828): Not enough parameters in call to function

<pre>
function StopTweenTint(this Region*, TweenStopResult result) {
  this.StopTweenTintRed(); // <------- line 1828
  this.StopTweenTintGreen();
  this.StopTweenTintBlue();
}
</pre>

Declaration of StopTweenTintRed is:
<pre>
import function StopTweenTintRed(this Region*, TweenStopResult result=Tween_STOP_RESULT);
</pre>

Tween module compiles correctly in both latest 3.3.5 and 3.4.0 releases.

**Comment by ivan-mogilko** [comment]
Actually, optional parameters do not work.

**Comment by sonneveld** [comment]
Do you have time to test if 3.3.5-section-05 compiles the tween module? There were a few conflicts around the default parameter handling, I'll check.

**Comment by ivan-mogilko** [comment]
Oh, that is a good question.
develop-3.3.5-section-05 *has same error*. I will find out when it was introduced and fixed.

**Comment by ivan-mogilko** [comment]
Okay, this error was fixed much later with 2167e7ba191388e26eb61b30dee23d377d0c4e06 (pull request: #310)

**Comment by ivan-mogilko** [comment]
As far as I can tell, 2167e7b can be applied to your merge result with only resolving one simple conflict (variable belongs to another struct in 3.4.0), and fixes the error, I guess we may accept this pull request now; the error will get fixed with corresponding section merged (section-19).

**Pull request merged**
