### PR TITLE
Dynamic arrays of non-managed struct and classic arrays of managed struct

### LINKED ISSUE #1818: AGS 4 / new compiler: support dynamic arrays of normal structs
I've been wondering, if it's possible to support dynamic arrays of non-managed structs?
For example:

```
struct Cell
{
    int data;
};

Cell cells[];
```
Above results with error in the extended compiler:
> Can only have dynamic arrays of integer types, 'float', or managed structs. 'Cell' isn't any of this.

(old compiler does not error on declaration, but on the `new` operator instead)

Right now this is restricted in both old and new compilers. Although, theoretically, you should be able to store an element of any size in dynamic arrays. Perhaps there have been a problem in coding accessing these elements, or anything else I cannot think of right now?

### PR DESCRIPTION
**Pull request by fernewelten**
Fixes #1818 and #2080.

The new compiler can now generate code for dynamic arrays of non-managed `struct`s and for classic arrays of managed `struct`s.

Also, you can define dynamic arrays of dynamic arrays and dynamic arrays of classic arrays.  These can be nested at any depth.

When there are pointers of entities that have pointers, then RTTI must be enabled.

## Dynamic array of non-managed struct
Typical code:
```
struct Warrior
{
    int Strength;
    int Health;
};

function room_FirstLoad()
{
    Warrior Lemmings[] = new Warrior[10];
    player.Say("That one's strength is %d", Lemmings[1].Strength);
}
```

`Lemmings` in `room_FirstLoad()` points to one chunk of memory where 10 structs are tucked side-by-side. `Lemmings[0]`, `Lemmings[1]` etc. will access the respective warriors, no need to initialise them individually with `new`. But the dynamic array itself must be initialised with `new[]`, as shown in the code above.

If you go that way, then the static struct (in this case, `struct Warrior`) must not contain any dynamic variable components, not even indirectly – unless RTTI is enabled. For instance, the following code will fail to compile, unless RTTI is enabled:

```
struct Stats
{
    int Stat[];    // ← dynamic component, not allowed unless RTTI is enabled
};    

struct Warrior
{
    Stats WarriorStats;
};

function room_FirstLoad()
{
    Warrior Lemmings[] = new Warrior[10];
}
``` 

## Classic array of managed struct

Typical code: 
```
managed struct Warrior
{
    int Strength;
    int Health;
};

function room_FirstLoad()
{
    Warrior Warriors[3, 10];
    for (int nationality = 0; nationality < 3; ++nationality)
        for (int citizen = 0; citizen < 10; ++citizen)
            Warriors[nationality, citizen] = new Warrior;
    player.Say("That one's strength is %d", Warriors[1][1].Strength);
}
```

`Warriors` in `room_FirstLoad()`is a chunk of 30 pointers tucked side-by-side. The classic array itself need not be initialised. But to get 30 usable components, you must initialise each of them with `new`, as shown in the code above.

The managed struct may not contain dynamic variable components unless RTTI is enabled, but that's nothing new.

## Dynamic arrays of dynamic arrays

This will only work when RTTI is enabled.

Here's code that defines and uses a dynamic array of a dynamic array of `short`s:

```
short Test[][]; 
int game_start()
{
    // Initialise a 3 by 3 array of arrays
    Test = new short[3][];
    for (int i = 0; i < 3; i++)
        Test[i] = new short[3];
    // Use an element
    Test[2][1] = 4711;
}
```

Here's code to define and use a dynamic array of a dynamic array of a managed `struct`:
```
managed struct Warrior
{
   int Strength;
   char Values[20];
};

int game_start()
{
    Warrior *Army[][];
    Army = new Warrior[3][];
    Army[2] = new Warrior[3];
    Army[1][2] = new Warrior;
    Army[1][2].Strength = 99;
}
```

You can nest the dimensions as deeply as you want. So `int Field[][][][][][];` is fine. You'll have to initialize the structure as follows:
- `Field = new Field[7][][][][][];`
- then `Field[i] = new Field[7][][][][];` (for all non-negative values of `i` that are lower than 7)
- then `Field[i][j] = new Field[3][][][];` (for all the combinations of `i` and `j` where `i` is lower than 7 and `j` is lower than 3)
- then `Field[ì][j][k] = new Field[5][][];` …
- … and so on until you come to `Field[i][j][k][l][m] = new Field[99];`

Limitation:
You can't define a classic array of a dynamic array, e.g., `int Field[][3, 5];` is forbidden. Once you've started with the dynamic markers `[]`, you can only add further dynamic markers to the right. 

On the other hand, you __can__ define a dynamic array of a classic array, e.g., `int Field[3, 5][][];`.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
> This addresses #1818 and #2080.

Please note that you can use keyword "Fixes" or "Resolves" in the ticket description, which will automatically bind this PR to the issue ticket, and also close the issue ticket when the PR is merged.

**Comment by ivan-mogilko** [comment]
> Classic array of managed struct

But was not this already supported, since the beginning? Or did something change in their regard?

**Comment by ivan-mogilko** [comment]
@fernewelten Hello, I see that you drafted this PR as something that would solve two feature requests. Is one of them is covered by the changes already? Seeing this has stalled, could that make sense to make a PR only for the first feature for now?

**Comment by fernewelten** [comment]
Thanks for the enquiry. I'm at it. I hope to be done in the next few days.

**Comment by fernewelten** [comment]
So here's the code for the PR. Note that I've force-pushed.

**Comment by ivan-mogilko** [comment]
Wow, this addresses even more features than before.

> Dynamic arrays of dynamic arrays

This means "jagged arrays" is not it? The relevant ticket was #1258.

I shall test this soon.

**Comment by ivan-mogilko** [comment]
Hmm, quick edit, could you clarify again, in the PR's description you say that this fixes #2080, which is "regular arrays of dynamic arrays". But further on you say "You can't define a classic array of a dynamic array". I cannot see any example for #2080 in the ticket's description either. So are these supported now, or not, and what is your opinion on the feature proposal itself?

Secondly, in the PRs description you mention "Classic array of managed struct", but these were already supported for a long time. Did anything change in their regard?

**Comment by fernewelten** [comment]
So this PR isn't about new concepts only. I've gone through the different cases of managed/non-managed entities and new/classic arrays that we offer so far and tried to describe them in a consistent system. Behind-the-scenes, I've refactored the relevant code, and these were the cases that I kept in mind that must all work or keep working.

**Comment by fernewelten** [comment]
When we have a declaration such as `int foo[3, 5][];` then there's the question in which direction it is read. Is `foo` a classic 3-by-5 array where each component is a dynamic array, or is `foo` a dynamic array where each component is a classic 3-by-5 array? 

The way I've implemented it, `foo` is a classic 3-by-5 array where each component is a dynamic array.  In an array of an array, the outermost dimension is specified and addressed __first__. (I explain my reasoning below.)

So `foo[0, 0]` is an element of the classic 3-by-5 array, which is a dynamic array. To initialise it, we'd need code such as `foo[0, 0] = new int[100];`. To initialise __all__ the elements of the 3-by-5 classic array, we'd need code such as, 
```
int foo[3, 5][];
for (int i = 0; i < 3; i++)
    for (int j = 0; j < 5; j++)
        foo[i, j] = new int[100];
```

The reason why I chose this way over the other is, what happens with `new`. We used to have a world where `[]` cannot be stacked. In this world, whenever a `[` follows `new TYPE` we initialise a dynamic array and the next integer defines the number of elements that must be created.
```
w = new Weapon*[100];
```

I wanted to keep that rule in a world where we can have `[][]`. For instance, consider the type, `Weapon*[][]`. To initialise this type we'd write `new Weapon*[`, and the next integer defines the number of elements to be created. So that leads to `w = new Weapon[100][];`. 

So generalising that, this means that in an array of an array, the __outermost__ dimension is written __first__.

**Comment by fernewelten** [comment]
You can have classic arrays where each component is a dynamic array, but you cannot have dynamic arrays where each component is a classic array. 

So currently, `int foo[][3, 5]` is disallowed: Once you start with `[]`, you can only tack on more `[]` to the right. For instance, `int foo[3, 5][][][]…` is allowed, to any nesting depth of the `[]`.

That's an implementation restriction that I might be able to release.

**Comment by ivan-mogilko** [comment]
@fernewelten Thank you for clarification!

> When we have a declaration such as int foo[3, 5][]; then there's the question in which direction it is read. Is foo a classic 3-by-5 array where each component is a dynamic array, or is foo a dynamic array where each component is a classic 3-by-5 array?
> The way I've implemented it, foo is a classic 3-by-5 array where each component is a dynamic array.

This makes total sense to me indeed.

> You can have classic arrays where each component is a dynamic array, but you cannot have dynamic arrays where each component is a classic array.
> So currently, int foo[][3, 5] is disallowed
> That's an implementation restriction that I might be able to release.

It's hard to tell how much of a priority that is.
Formally speaking, strictly in terms of memory, is not dynamic array of regular arrays about same thing as dynamic array of structs? as in you have a dyn arr of a sequence of bytes in both cases.
Note: after your PR you may have dynamic arrays of structs which wrap classic arrays in them.

**Comment by ivan-mogilko** [comment]
So, I tested your PR for all 3 new features, and they seem to work!

<details>
<summary>The script I used is under spoiler</summary>

```
struct NormalStruct
{
	int a, b, c;
	float f1, f2, f3;
};

void Test_DynArraysOfStructs()
{
	NormalStruct dynarr[];
	dynarr = new NormalStruct[10];
	
	for (int i = 0; i < dynarr.Length; ++i)
	{
		dynarr[i].a = 10 + i;
		dynarr[i].f1 = IntToFloat(i) * 3.33;
	}
	
	Display("NormalStruct at index %d is: %d, %f", 5, dynarr[5].a, dynarr[5].f1);
}

void Test_StaticArraysOfDynArrays()
{
	Character* arr[10][];
	
	for (int i = 0; i< 10; ++i)
	{
		arr[i] = new Character[10];
	}
	
	arr[5][6] = player;
	
	Display("Character at static arr %d, dyn arr %d = %s", 5, 6, arr[5][6].Name);
	
	Character* dynarr[] = arr[5];
	
	Display("Character at dynamic arr %d = %s", 6, dynarr[6].Name);
}

void Test_JaggedArrays()
{
	NormalStruct jagarr[][][];
	
	jagarr = new NormalStruct[10][][];
	jagarr[2] = new NormalStruct[40][];
	jagarr[5] = new NormalStruct[60][];
	jagarr[2][22] = new NormalStruct[300];
	jagarr[5][55] = new NormalStruct[600];
	jagarr[2][22][222].f2 = 0.222;
	jagarr[5][55][555].f2 = 0.555;
	
	Display("jagarr[%d][%d][%d].f2 = %f", 2, 22, 222, jagarr[2][22][222].f2);
	Display("jagarr[%d][%d][%d].f2 = %f", 5, 55, 555, jagarr[5][55][555].f2);
}

struct StructWithArray
{
	int arr[100];
};

void Test_DynArraysOfStatArrs()
{
	//int dynarr[][5];
	//dynarr = new int[5][5];
	// !!! THIS DOES NOT WORK AT THE MOMENT !!!
	
	StructWithArray dynarr[];
	dynarr = new StructWithArray[5];
	dynarr[2].arr[50] = 10;
	
	Display("%d", dynarr[2].arr[50]);
}


function game_start()
{
	Test_DynArraysOfStructs();
	Test_StaticArraysOfDynArrays();
	Test_JaggedArrays();
	Test_DynArraysOfStatArrs();
}
```

</details>

This is going to be a good addition to the AGS script syntax.

**Comment by ivan-mogilko** [comment]
Found couple of errors.

1. It's possible to assign a jagged (multi-dimensional) dynamic array's pointer to a dynamic array of more dimensions, if you do this through accessing an array's element
```
        int arr1[][];
	arr1 = new int[10][];
	arr1[5] = new int[20];
	
	int arr2[][];
	arr2 = mdim[5]; // the 5th element is a 1-dimensional array of ints
```
You may then proceed accessing this second array, writing and reading elements in it. It works, but I suspect that memory contents become incorrect after this.

2. There's a corruption in one error message again (I remember there have been a similar problem in the past). Use following script:
```
        int arr[];
	arr[1][2] = 10;
```
The compiler prints following error message:
> NewArrays.asc(76): An array index cannot follow an expression of type 'ЊЗќ'

(the garbage may vary of course)

**Comment by fernewelten** [comment]
Okay, I'm on it. :)

**Comment by fernewelten** [comment]
Adding a better typecheck and fixing the 'c_str()' bug.

**Comment by ivan-mogilko** [comment]
I confirm these issues were fixed.

**Pull request merged**
