### PR TITLE
Editor: Change room icon for state saving rooms

### PR DESCRIPTION
**Pull request by AlanDrake**
Implements different rooms icon, depending if the room saves state or not.
Should be a nice-to-have if we stop relying on room number to decide if a room saves state.

I reused pre-existing icons, but I could make an alternate version where the diskette remains colored even when the room is not loaded to make it more visible:
immagine

Opened:
immagine

### CODE REVIEW

**Comment by ericoporto** [comment]
They are so cute! Now I noticed that the other room icon has the area masks there, super interesting.

**Comment by AlanDrake** [comment]
I did a quick mockup, diskettes only look readable when black or blue

immagine

So, do I make a new icon with colored diskette? (blue or black?)

**Comment by ericoporto** [comment]
I think the blue one is the best one.

Sorry for the trouble 😬

**Comment by AlanDrake** [comment]
Alright, redone with the blue one.

**Comment by ericoporto** [comment]
Weird, the files change tab only contains the change to csproj file and the change in script but no new icon added. :/

**Comment by AlanDrake** [comment]
My bad, I had resetted to make less useless changes in the csproj and frogot to readd the new icon.

**Comment by ericoporto** [comment]
I think it's still missing one icon (either the grayed out one or the non-grayed out one)

**Comment by AlanDrake** [comment]
I only created the "grayed out with blue disk" icon, everything else are pre-existing resources, so this is correct.

**Pull request merged**
