### PR TITLE
AGS 4: Support reading from game assets in script

### PR DESCRIPTION
**Pull request by ivan-mogilko**
For #1227 (does only engine part of the job).

This supports reading resource files ("assets") in script. Resources are retrieved using engine's own AssetManager, thus the script has access to everything that engine has. This method allows to open files only in read mode.

The opened file stream is modified to restrict reading and seeking to the range of offsets: this ensures that the script won't read past the end of resource even if it's retrieved from the larger file (package).

To specify game resource a new path token is introduced: "$DATA$".

Following script functions support this token:

**File.Open** - opens resource file for reading (if script asks to open for writing it will throw an error and return null pointer, as usual).
Example: `File* f = File.Open("$DATA$/myfile.dat");`

**DynamicSprite.CreateFromFile** - will try to create a sprite from the bitmap in game resources.
Example: `DynamicSprite* dspr = DynamicSprite.CreateFromFile("$DATA$/custom.bmp");`

**ListBox.FillDirList** - will fill list box with all found resource names using wildcard pattern.
Example: `MyListBox.FillDirList("$DATA$/room*.crm");` - this shows a list of all room files in the game.

### CODE REVIEW

**Comment by ericoporto** [comment]
So, I tried the following, I saved a poem in a `poem.txt` file, renamed it to `poem.wav`, and imported with the Editor.

```
function hGlowingOrb_AnyClick()
{
  File* f = File.Open("$DATA$/au000001.wav",eFileRead);
  if(f == null) { Display("no file found"); return; }
  while(!f.EOF) { Display(f.ReadRawLineBack()); }
}
````

It works if I build the `.exe` and run it, but it doesn't work if I run in the debug mode in the Editor.

**Comment by ivan-mogilko** [comment]
That was because when running in debug mode it does not pack sounds into the game but reads clips from audiocache, and audiocache is registered using special filter to maintain classic search rules... anyway, I made it ignore these filters when opening assets with $DATA$ token.

**Comment by ericoporto** [comment]
Yeah! Now both works! And I could draw a bitmap I got from an "audio" file!

**Comment by ivan-mogilko** [comment]
Well, after this there's still a task of adding custom files in the project, but meanwhile this workaround with substituting one of the existing resource types may also be used.

**Pull request merged**
