### PR TITLE
Android: AGS Player add per game button options

### PR DESCRIPTION
**Pull request by ericoporto**
add a button with three dots on each game entry in the ags player to invoke the context menu of the item.

image

following this [comment](https://github.com/adventuregamestudio/ags/issues/1871#issuecomment-1405353587)

> there's no visual indication that you may open them for a particular game (no button/icon besides the game title).

### CODE REVIEW

**Comment by ericoporto** [comment]
@ivan-mogilko to reduce trouble testing this, I added here the fix for storage access in the AGS Player, for Android 10 and above

**Comment by ivan-mogilko** [comment]
Okay, good news is that directory permissions work again now, so that is fixed; I will report the rest of test results bit later.

**Comment by ivan-mogilko** [comment]
So, the custom game preferences seem to work fine, as far as I can tell.

Global preferences, on the other hand, work strangely. It looks like they work the first time after you opened them, and then run the game (even if you haven't changed anything). But if you launch AGS Player again, and run the game right away, then, it seems like all options are reset to defaults (software renderer, absolute cursor movement, and so on).

**Comment by ericoporto** [comment]
I am not 100% sure but I think the problem is this here: https://github.com/adventuregamestudio/ags/blob/e069c3f51c08c163df023157e99e14bbcefd317a/Engine/platform/android/acpland.cpp#L101

So it would be using different directories as base dir, need to think a bit on how to properly fix in a way that is good for the single game player too.

But the changes here are not related to that, so if you want to merge it should be fine, if not then it's alright too, but I need to think a bit on how to properly fix this.

**Pull request merged**
