### PR TITLE
Add emscripten improvements

### PR DESCRIPTION
**Pull request by ericoporto**
- AGS Script errors and messages use Alert boxes on browsers too
- A new directory is used by the engine, `/home/web_user/saved_games`, files saved there are persisted (config and save slots)
- A new modal ui is added to be able to clear these files
- We leverage this modal ui to add an extra button for toggling fullscreen. Exiting fullscreen is accomplished by using Esc key (in mobile browsers, default exiting of fullscreen using back gesture also works). Alt+Enter still works the same.

I already updated here https://ericoporto.github.io/agsjs

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
Question: do all file writing operations need the "syncing with fs", or strictly save game and config file?

If all of them need this, perhaps it would be better to implement a function call when closing a writeable File object instead.

**Comment by ericoporto** [comment]
First, let me explain what FS.syncfs, this operation can be used to save all files that in directories with a mounted IDBFS to disk. While this happens, the browser tab does a slight hang, but the operation can be asynchronous in theory - we could have a worker that does this if we want to minimize this hang. We can't pass a specific file, so it always sync everything that can be synced.

So in theory, if we knew when the user would stop playing the game, but before closing, we could sync just there, instead of everytime, but when I tried this, this didn't work for all cases - say the browser is closed suddenly.

> If all the file writes need this, then it would be better to implement a function call when closing a writeable FileStream object instead. This will ensure that whenever engine writes and closes a file this action will be performed.

So there are two things here

- Adding a platform specific thing in the FileStream, is this ok?
- It would be nice to know we actually need to sync, knowing this is a write operation in a "permanent storage" location, but at the time of closing the file, but I couldn't quite figure this out.

> Question: do all file writing operations need the "syncing with fs", or strictly save game and config file?

I think most of the time people write to a config file some stuff and savegame, so it felt a way to smash at least two file syncs in one. Most of the time these save games happen in places (menus, quiet areas) where it's alright to hang the game a bit while it saves to disk.

> Why "post-savegame" and "post-config" actions should be separate platform functions?

Oh, I tried to follow the existing "Post" stuff, and it looks like Config and Savegame can be different directories. If it's acceptable they could be some single platform method.

**Comment by ivan-mogilko** [comment]
> So in theory, if we knew when the user would stop playing the game, we could sync just there, but this doesn't work when the browser is closed suddenly.

Hmm, looks like I misunderstood. Then I'll ask a different question: what is the purpose of "syncing", or rather, which problems might occur if we do not sync?

If this operation is required, for example, to be able to open a file for reading after it's being written, then it has to be enforced after writing.

But, if this operation is moving files from some "temporary" location to a "permanent" one, then perhaps a worker thread with some "please sync now" signal call would work better.

The worker thread that syncs periodically will be useful, because AGS game may have custom saves, or other custom files that should be saved while user may not save the game itself.

**Comment by ericoporto** [comment]
The virtual filesystem we use for AGS is in ram (MEMFS). We can FS.mount a IDBFS filesystem in any directories - currently the saved_games dir.

FS.syncfs is an operation that you can either populate from IndexedDB, or store back to IndexedDB (disk), files in mounted directories - it has a parameter "populate" that can be true or false. The operation we are discussing is writing to disk (populate=false).

> Hmm, looks like I misunderstood. Then I'll ask a different question: what is the purpose of "syncing", and which problems might occur if we do not sync?

Not syncing means the game doesn't store the files it changed back into disk.

> The worker thread that syncs periodically will be useful

There's a small catch that I couldn't yet figure how to do this without pthreads - which require an inconvenient header.

> so, to clarify more, there are files that should be in permanent storage, and those that should not; how is it decided which are which?

So only files in the `/home/web_user/saved_games` dir are stored in the IndexedDB permanent storage.

---

This is not the ONLY permanent storage in the browser, say we want to install the game and have it behave like an app, the game files (game.ags, speech.vox, ...) they have a different browser API they go through - I haven't implemented yet, but once this is created a new button will appear in the address bar for installation.

**Comment by ivan-mogilko** [comment]
Hm, so, if I understand correctly, the platform code explicitly defines that certain *directory* is going to be "synced". In other words, it's not certain "objects" or files of certain purpose (save, config) that are synced, but files that are written to particular directory (user's save directory).

In such case, in my opinion, the new platform functions that are introduced here are going to be misleading, because they hide the intent: what important is not that "save" or "config" is made, but that something is written to the particular dir. There are  few issues with this:
* These files may in theory be written by the script File API (at least the config file, there's even a $CONFIGFILE$ tag introduced in recent version);
* This assumes that the save and config are always written to the "save dir" defined by the platform, which may not be the case (even if only hypothetically speaking).
* This ignores a situation when any custom user file is written to "save dir".
* I think (judging by the code in your pr), that it currently ignores any file or serialization errors; so it may ask for a sync when writing failed completely.

I think that in such circumstance a platform code should react to a signal telling that *something is written to the particular directory*. Then it could check the path and decide *for itself* whether this is a permanent location or not; because it's "platform" that knows these nuances, not the engine.

This brings us back to the previous suggestion about FileStream.

For example, FileStream could record the filepath (something that would be useful in any case, for debugging).
(Whether "what" was written is necessary to tell or not is a separate question, this may be also added to Stream class, or passed somehow else, but I think this may be postponed until actually needed.)
The problem would then be to invent how to pass the signal from the closing FileStream into the platform code. This is mostly a problem of organizing a code, since "platform driver" is currently in engine, while FileStream is the utility class in the Common lib.

The second part, since you mentioned sync/async issue, is making sure that this operation won't block the game too much.

Now, I don't know or don't remember what is this problem with threads in Emscripten (I believe it should be resolved the earlier the better, because it will complicate things every time we'll decide to utilize a thread for background work).

Unless there's a way to use some emscripten's library utility to run this action async, normally, I'd say, there should be a working thread started but sleeping most of the time, until there's a signal about written file closed, in which case it wakes up and run file sync. Or maybe two kinds of signals: one that only tells to write when possible (to avoid too many syncs often), and another that asks to do it immediately for important files. But I am theorizing now.

If we cannot use threads, neither run this async no matter what now, I might suggest to design a workaround in such way that would *pretend* that it runs async. This is to make our intent clear, and also prepare a "foundation" for the proper solution.
Perhaps it could be done like this: a FileStream tells what it writes on close, a platform decides if that should be synced to a persistent location, but does not sync immediately and increments some counter. Finally, there may be introduced a platform driver's method, which is explicitly meant to ask for immediate file syncing (might need to find a good name). This method will see if a counter > 0, and if it's then sync and reset the counter.

**Comment by ericoporto** [comment]
> I don't know or don't remember what is this problem with threads in Emscripten

I need Coop+Coep headers for SharedBuffer Arrays ([see more here](https://web.dev/coop-coep/)), which are used to implement threads, but most free webhosts doesn't serve them. After [I started nagging](https://itch.io/t/1028526/cross-origin-policies-for-webassembly), there is now [some experimental support at least in itch](https://itch.io/t/2025776/experimental-sharedarraybuffer-support), but not in GH pages, or gamejolt or elsewhere.

> If we cannot use threads,

We can't - maybe in the future, but not right now.

For the asynchronous part, ignoring Emscripten, the issue is #1618 - that issue is a specialization of the Commit problem from Switch Homebrew I mentioned earlier which is similar to here, file operations happen in a fast but ram location and pushing to a permanent storage can hang a bit.

> The problem would then be to invent how to pass the signal from the closing FileStream into the platform code.

If there was say some default callback on Common that we could override in the Engine by a platform one, then I could use this on the platform driver.

It's good to see if this callback would work for your suggested implementation. #1349 would make implementing this really easy, I think right now such code goes in as some custom even in the SDL event queue?

> I think (judging by the code in your pr), that it currently ignores any file or serialization errors; so it may ask for a sync when writing failed completely.

The write of the FileStream is to RAM, and yes it can fail if we are low on RAM.

**Comment by ivan-mogilko** [comment]
> If there was say some default callback on Common that we could override in the Engine by a platform one, then I could use this on the platform driver. (A hacky way would be to use the extern to link to something in Engine)

Yes, callback seem to be a better option than having an extern, because then we'd have to implement that extern function in every program that links the FileStream.

Let's say, if there were a static FileStream's member, a function pointer that accepts some args, or maybe 1 arg which is a struct with necessary fields (latter will be easier to expand when needed). And called in `FileStream::Close()`:
```
if (_fileCloseNotify)
{
    _fileCloseNotify(args);
}
```

I don't think this will add any noteable overhead, as closing a file is not something that happens alot and often.

I doubt that SDL event is a way to go here though, as theoretically a reaction to this callback may have to be instantaneous.

**Comment by ericoporto** [comment]
Hey, I need to just check how to organize things and fix building in other platforms, but it appears to work well. I added the build in the [agsjs](https://ericoporto.github.io/agsjs/)

**Comment by ericoporto** [comment]
Hey, it appears to work well. I added the build in the [agsjs](https://ericoporto.github.io/agsjs/).

I haven't yet rebased to replace the previous commits with the new way as I am curious if this implementation is acceptable.

**Comment by ericoporto** [comment]
Hey, it appears to work well. I added the build in the [agsjs](https://ericoporto.github.io/agsjs/). (did a quick update there now)

I ended going for `std::function` because I wanted to capture the context of the current platform driver in the lambda I used. In this way I used less globals as possible and kept the methods in the Emscripten platform driver.

I reorganized the commits a bit. I erased from the commits of this PR the original syncfs attempt using the PostSaveGame and PostSaveConfig.

I placed the old commits I did here, in case you need them to help review: https://github.com/ericoporto/ags/tree/add-emscripten-improvements-old

**Comment by ivan-mogilko** [comment]
Yes, this will work.

**Pull request merged**
