### PR TITLE
Update installer for 3.5 release

### PR DESCRIPTION
**Pull request by morganwillcock**
As well as the changes described in #875 this also:

- Adds Git ignores for Installer directory
- Switches all website URLs to use HTTPS
- Updates Inno Seup details in the license file
- Stops the web browser being opened as an elevated process if the installer self-elevated
- Adds a status message when installed Visual C++ runtime
- Stops the web browser opening when running in silent mode

Any testing would be appreciated, I've only tried Windows 7 (in various states) and Windows 10 (but was trying not to break it).

### CODE REVIEW

**Comment by morganwillcock** [comment]
I think checksum verification may depend on the working directory, so I'll re-check this.

**Comment by morganwillcock** [comment]
Any objections to me merging this now?

**Comment by sonneveld** [comment]
This looks good to me. Did you say that you found someone to test XP?

**Comment by morganwillcock** [comment]
This version of .NET isn't available for XP. Unless you mean, did I test how it fails on XP? I could add a check for the Windows version and tell the installer to exit if the version isn't Vista or newer. I'm not sure what the defaults for WINE are though, it probably identifies itself as XP by default.

**Comment by morganwillcock** [comment]
It looks like this file was intially commited with Unix line endings, but the Inno Setup editor writes Windows lines endings for any changes that are made. I've rebased the changes and switched the line endings, so they are at least consistent.

The other change was to pop-up a message box if the Windows version is too old, but the installer will still carry on running rather than exit.

**Pull request merged**
