### PR TITLE
Automatic font outlines

### PR DESCRIPTION
**Pull request by fernewelten**
Have a look: This is proposed code for issue #878 (automatic outlines).
Added two additional fields to fonts:
- `AutoOutlineStyle` (`Rounded`, `Squared`).
- `AutoOutlineThickness` (positive integer, or 0 for default) 
(I couldn't use "1" as the default for `AutoOutlineThickness` because currently, scaled bitmap fonts get an outline that is thicker than 1). 

The fields will only show in the editor if `OutlineStyle==Automatic`.
The field `OutlineFont` will now only show if `OutlineStyle==UseOutlineFont`.

The algo for generating the outline is based on messengerbag's. The text is only rendered _once_ per outline into a local bitmap; from then on, the bitmap is blitted repeatedly. Another local bitmap accumulates the vertical blits. In all, the number of blits is proportional to the thickness of the outline. 

For anti-aliased ttf fonts, a thickness of 2 to 3 seems to work nicely.

What do you think?

### CODE REVIEW

**Comment by rofl0r** [comment]
why are there commits of ivan in the commit list ?

**Comment by ivan-mogilko** [comment]
Oh, it seems this is because the PR is based on release-3.5.0 branch, but aimed for ags3 which does not have latest 3.5.0 merged in yet.

**Comment by fernewelten** [comment]
> rebase your feature branch on top of "ags3"?

Can do.

**Comment by fernewelten** [comment]
> Can do.

Cannot do. And I'm to exhausted to fight git right now. It's easier to open a new pull request, this time with no more than the correct commits, under the same short name. And cleaner, too. See #892.

Sorry.

**Pull request closed without merging**
