### PR TITLE
Editor: Default Setup has new Android relevant options

### PR DESCRIPTION
**Pull request by ericoporto**
- Added mouse_emulation, mouse_control_mode and show_fps

partial of #1819

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
The "control enabled" option won't work like that, because it has different meanings on mobile and desktop. It has to be separated on settings pane.

**Comment by ivan-mogilko** [comment]
Hm, so, this also brought me to realization that mouse speed no longer works in 3.6.0... or maybe it was not restored properly.

**Comment by ericoporto** [comment]
About the hints, it should be fine to apply both for speed independently of what's set - If I remember correctly, it's possible to set relative mode in-game at runtime.

**Comment by ivan-mogilko** [comment]
So, my suggestion for this is:
* Rename "ControlEnabled" (enum and property) to something like "MotionMode/Method" which is either Direct or Relative, and place it into the "Touch" category. Write only into android.cfg for now (this may be adjusted later if more platforms require this).
* A less important proposal, but imho it's better to have EmulateMouseType have a name which references "Touch", as in theory there may be several different mouse emulations (with other input devices). Could be TouchToMouseEmulation, or similar.

I also noticed that the mouse speed is saved as integer multiplied by 10 in android.cfg. I don't know all the reasons for this, but apparently this is because engine must return `int` values when passing preferences? I think this is a mistake of data format following GUI and/or internal program limitation, and the setting should be stored as it is stored in acsetup.cfg, while the conversion rather be done inside the program itself.

**Comment by ivan-mogilko** [comment]
Added your commit, with additional changes:
197e1b2b6dc614043be521f18747ebf71ee4a2b1
9f50b653d5984f7d52b31a1dc570abf6360a0919

**Pull request closed without merging**
