### PR TITLE
Modifies palrender plugin for leaner agsplugin.h

### PR DESCRIPTION
**Pull request by ericoporto**
Should fix building palrender plugin on ags4 branch. I have acquired a test game and will test soon and report.

### CODE REVIEW

**Comment by ericoporto** [comment]
I think I got everything, I can modify the PR if desired.

[reflectiosn](https://streamable.com/7o41e)

Scavenger provided me a demo game project to test it, I need to talk with him if someone desire's to access it privately.

The plugin part of the game that shows the reflections appears to work, but I have a weird segfault non-related to the plugin if I try to scroll the inventory:

```
prepare_characters_for_drawing() 0x0000000000578b41
prepare_room_sprites() 0x0000000000579bba
construct_game_scene(bool) 0x0000000000579d99
render_graphics(AGS::Engine::IDriverDependantBitmap*, int, int) 0x000000000057a5c1
UpdateGameOnce(bool, AGS::Engine::IDriverDependantBitmap*, int, int) 0x00000000005bd81b
<unknown> 0x00000000005bdd7f
RunGameUntilAborted() 0x00000000005bdf85
initialize_start_and_play_game(int, char const*) 0x00000000005be223
initialize_engine(std::map<AGS::Common::String, std::map<AGS::Common::String, AGS::Common::String, std::less<AGS::Common::String>, std::allocator<std::pair<AGS::Common::String const, AGS::Common::String> > >, std::less<AGS::Common::String>, std::allocator<std::pair<AGS::Common::String const, std::map<AGS::Common::String, AGS::Common::String, std::less<AGS::Common::String>, std::allocator<std::pair<AGS::Common::String const, AGS::Common::String> > > > > > const&) 0x00000000005b6093
ags_entry_point(int, char**) 0x00000000005c39d6
__libc_start_main 0x00007f42dd0d5b97
_start 0x00000000004b3dc7
```

There's an additional note that this game only works with Software Drawing - because is a game with palette manipulation.

**Comment by ivan-mogilko** [comment]
Sorry for such delay, I finally got a moment to check this out.

@ericoporto it seems that your last commit changes line endings, breaking change history for the whole file, could you redo that?

**Comment by ericoporto** [comment]
I can! Good catch, for some reason I had not noticed!

**Comment by ivan-mogilko** [comment]
> but I have a weird segfault non-related to the plugin if I try to scroll the inventory:

Could you elaborate, how do you scroll inventory? I was not able to reproduce this yet (using your PR branch).

**Comment by ericoporto** [comment]
@ivan-mogilko I scrolled with the up and down arrows at the right.

**Comment by ivan-mogilko** [comment]
@ericoporto the moment I run this game using Release configuration, it begins to crash.

The problem is that plugin uses one variable without properly initializing it, and it causes unwanted effects later: https://github.com/adventuregamestudio/ags/blob/master/Plugins/agspalrender/ags_palrender.cpp#L1647

Try replacing this with `bool scaled = false;` and see if your crash is still happening.

**Pull request merged**
