### PR TITLE
Disable Werror on C# projects

### PR DESCRIPTION
**Pull request by persn**
As discussed in #408. The Werror property seems to have beends randomly set across projects and build configs so it was good we looked into this

### CODE REVIEW

**Comment by tzachshabtay** [comment]
@rofl0r continuing the discussion from #408 here. An alternative suggestion: remove werror as you suggest from the projects, but keep using it in the CI build. So you wouldn't need to worry about fixing other people warnings as you load the project using your favorite compiler, but you wouldn't be able to create new warnings for everyone.

**Comment by rofl0r** [comment]
@tzachshabtay that sounds like a great idea!

**Comment by persn** [comment]
Just out of curiosity, how do you configure the repo so that the C# projects uses Werror only on the build server? If this is more complex than originally imagined we could simply just toggle Werror so that it's active for Release builds only.

**Comment by rofl0r** [comment]
maybe like this:
in CI script before build:
```sh
sed -i 's/TreatWarningsAsErrors>false/TreatWarningsAsErrors>true/g' foo.csproj
```

**Comment by ivan-mogilko** [comment]
I apologize for delay, was busy with other matters.

Was there any conclusion on this?

**Comment by persn** [comment]
If what @rofl0r says works, we can do that assuming no one disagrees.

**Pull request merged**
