### PR TITLE
Implemented basic functionality for --tell command

### PR DESCRIPTION
**Pull request by ivan-mogilko**
For #520

* Engine detects command line arguments starting with `--tell-`, the suffixes are stored in a set as keys.
* If there was at least one such argument, engine will print out requested info to std out and stop. Because some of this info requires data from the game header, printing is done after game files were found and pre-read.
* Information is printed out in JSON format and may contain multiple key/value pairs and groups of those.

TODO and potential issues:
* **[DONE]** Engine prints some other messages to std out, such as its name and version, game location and version, maybe some warnings and errors. Should these be suppressed to simplify parsing for external process?
* **[DONE]** Need to detect early whether it is required to read game at all, because some of the info may not need that (like, if we need to print only list of supported gfx drivers);
* Need to figure out good names for the keys. I called implemented one "config-meta" because it contains settings that help to find and work with config, but maybe there are better alternatives.
* Implement a minimal necessary set of info keys, as noted in #520.

### CODE REVIEW

**Comment by ericoporto** [comment]
About suppression of name and version, I think it would be best. This would make the output pure json, easier to parse. Other possiblity is, in such case of suppression, add also these information as elements in this json.

**Comment by morganwillcock** [comment]
OK, I built this and tried it out:
<pre>./ags --tell data
Adventure Game Studio v3.5 Interpreter
Copyright (c) 1999-2011 Chris Jones and 2011-2019 others
ACI version 3.5.0.15

Initializing allegro
Initializing game data
Located game data file: /Users/mwillcock/Downloads/In-Bloom/data/In-Bloom.ags
Opened game data file: game28.dta
Game data version: 49
Compiled with: 3.4.1.14
"config-meta":{"gamename":"In Bloom","defaultconfig":"/Users/mwillcock/Downloads/In-Bloom/data/acsetup.cfg","globalconfig":"./acsetup.cfg","userconfig":"/Users/mwillcock/Library/Application Support/In Bloom/acsetup.cfg"}</pre>

The first issue is, a lot of the benefit of outputting in json is lost when you have to actually locate the json in the the output. So I think it would be best to just output *only* the json, but in a style that could also be processed line-by-line:

<pre>{
	"gamename": "In Bloom",
	"defaultconfig": "/Users/mwillcock/Downloads/In-Bloom/data/acsetup.cfg",
	"globalconfig": "./acsetup.cfg",
	"userconfig": "/Users/mwillcock/Library/Application Support/In Bloom/acsetup.cfg"
}</pre>

i.e. if doing something where there is no JSON decoder you've at least got a chance of reading the data by searching for the line that starts with the key you are interested in. I'm not saying this is promoted way to use the output, just that `grep '"gamename"'` might be good enough when you have nothing better.

Associated with this, I don't think there should be any output going to stdout other than the JSON, so all the preceding lines shouldn't be present (they should be part of the JSON output if they are relevant), and if there is an error it needs to go to stderr. It should also set the appropriate error code (not just for this --tell command, but whenever there is a query or launch failure). The usage message can still go to stdout, because that should only be present on an error or when requested.

As a psuedo example of what I mean, when the errors go to correct place and you know whether an error occurred or not, there should be no additional work needed to process the JSON string:
<pre>process = new Process("ags --tell data");
process.Run();

if (process.exit_code == 0) {
    # stdout is guaranteed to be JSON only
    json.Decode(process.stdout);
} else {
    Print("Something went wrong");
    # print the error but not the usage message
    Print(process.stderr);
}</pre>

**Comment by morganwillcock** [comment]
Here is a working (probably Linux and macOS) script that could be used to test the changes that I suggest. This tests the error codes, splitting the output between stdout and stderr, and reading the JSON without a JSON decoder.

<pre>#!/bin/sh

./ags --tell data >stdout 2>stderr

if [ $? -eq 0 ]; then
	printf "Game name: "
	sed -E '/^[[:blank:]]"gamename":/ { s/.*"(.*)",?$/\1/; q; }; d' stdout
else
	echo "An error occured!"
	cat stderr
fi</pre>

**Where success is equivalent to:**
<pre>#!/bin/sh

echo '{
	"gamename": "In Bloom",
	"defaultconfig": "/Users/mwillcock/Downloads/In-Bloom/data/acsetup.cfg",
	"globalconfig": "./acsetup.cfg",
	"userconfig": "/Users/mwillcock/Library/Application Support/In Bloom/acsetup.cfg"
}'</pre>

**And an error is equivalent to:**
<pre>#!/bin/sh

echo Error reading game data > /dev/stderr
echo Usage:
echo This is how you use it
exit 1</pre>

**Output on success:**
<pre>Game name: In Bloom</pre>

**Output on failure:**
<pre>An error occured!
Error reading game data</pre>

**Comment by ivan-mogilko** [comment]
Ammended, please try now.

**Comment by morganwillcock** [comment]
> PS. Also, does it have to add \t to indent json, or linebreaks is enough?

Well, it depends whether you want it to be easier to read by eye, vs slightly more complex to parse. I guess that since my argument is to parse with as a basic a tool as possible, lack of whitespace is probably a good thing as it means you don't have to check for optional characters.

Technically, this isn't [valid JSON](https://jsonlint.com/) though, because of the first line:

<pre>$ ./ags --tell data
"config-meta":
{
"gamename":"In Bloom",
"defaultconfig":"/Users/mwillcock/Downloads/In-Bloom/data/acsetup.cfg",
"globalconfig":"./acsetup.cfg",
"userconfig":"/Users/mwillcock/Library/Application Support/In Bloom/acsetup.cfg"
}</pre>

And on failure the return code is still 0:

<pre>$ ./ags --tell data2
ERROR: Unable to determine game data.
Defined game location is not a valid path.
Path: '/Users/mwillcock/Downloads/In-Bloom/data2'
Usage: ags [OPTIONS] [GAMEFILE or DIRECTORY]

Options:
  --fps                        Display fps counter
  --fullscreen                 Force display mode to fullscreen
  --gfxdriver <id>             Request graphics driver. Available options:
                                 ogl, software
  --gfxfilter <filter> [<scaling>]
                               Request graphics filter. Available options:
                                 hqx, linear, none, stdscale
                                 (support differs between graphic drivers);
                                 scaling is specified by integer number
  --help                       Print this help message and stop
  --hicolor                    Downmix 32bit colors to 16bit
  --log                        Enable program output to the log file
  --no-log                     Disable program output to the log file,
                                 overriding configuration file setting
  --version                    Print engine's version and stop
  --windowed                   Force display mode to windowed

Gamefile options:
  /dir/path/game/              Launch the game in specified directory
  /dir/path/game/penguin.exe   Launch penguin.exe
  [nothing]                    Launch the game in the current directory

$ echo $?
0
</pre>

Also the error "ERROR: Unable to determine game data." isn't going to stderr:

<pre># redirect stdout but don't touch stderr
./ags --tell data2 > /dev/null</pre>

Also, I wasn't sure why the defined error codes were negative (unless I misunderstand how they are used):
<pre>#define EXIT_NORMAL 0
#define EXIT_ERROR  -1
#define EXIT_CRASH  -2</pre>

0, 1, and 2 would be fine.

**Comment by ivan-mogilko** [comment]
I did some additional fixes. TBH don't know what was wrong with return code earlier, it correctly displays non-0 value for me when I test this out.

There's currently one issue that if failing to find a game it will still print "help" into stdout. I will think more, maybe redo previous commits in different way to guarantee such does not happen by mistake.

**Comment by morganwillcock** [comment]
Ah, I was assuming the result would be a flat name space rather than having a hierarchy, so to contradict myself slightly, if you have named sections like "config-meta" or "graphics-driver" the indent would be beneficial to indicate how deep in the structure you are. So for example, given a single line from here:
<pre>{
	"config-meta": {
		"gamename": "In Bloom",
		"defaultconfig": "/Users/mwillcock/Downloads/In-Bloom/data/acsetup.cfg",
		"globalconfig": "./acsetup.cfg",
		"userconfig": "/Users/mwillcock/Library/Application Support/In Bloom/acsetup.cfg"
	}
}</pre>
...the tab count also gives you the depth within the structure.

Printing errors to stderr seems to work now:
<pre>$ ./ags --tell data2 > /dev/null
ERROR: Unable to determine game data.
Defined game location is not a valid path.
Path: '/Users/mwillcock/Downloads/In-Bloom/data2'</pre>

The return code on failure is still 0 for me:
<pre>./ags --tell data2
ERROR: Unable to determine game data.
Defined game location is not a valid path.
Path: '/Users/mwillcock/Downloads/In-Bloom/data2'
Usage: ags [OPTIONS] [GAMEFILE or DIRECTORY]

Options:
  --fps                        Display fps counter
  --fullscreen                 Force display mode to fullscreen
  --gfxdriver <id>             Request graphics driver. Available options:
                                 ogl, software
  --gfxfilter <filter> [<scaling>]
                               Request graphics filter. Available options:
                                 hqx, linear, none, stdscale
                                 (support differs between graphic drivers);
                                 scaling is specified by integer number
  --help                       Print this help message and stop
  --hicolor                    Downmix 32bit colors to 16bit
  --log                        Enable program output to the log file
  --no-log                     Disable program output to the log file,
                                 overriding configuration file setting
  --version                    Print engine's version and stop
  --windowed                   Force display mode to windowed

Gamefile options:
  /dir/path/game/              Launch the game in specified directory
  /dir/path/game/penguin.exe   Launch penguin.exe
  [nothing]                    Launch the game in the current directory

$ echo $?
0</pre>

> There's currently one issue that if failing to find a game it will still print "help" into stdout. I will think more, maybe redo previous commits in different way to guarantee such does not happen by mistake.

I think as long as the error code is always correct, and the usage message always go to stdout (if this is the 'help' you are talking about), this is probably the most straight forward way to separate the help from the errors. So I think usage messages should only ever go to stdout.

**Comment by ivan-mogilko** [comment]
> I was assuming the result would be a flat name space rather than having a hierarchy, so to contradict myself slightly, if you have named sections like "config-meta" or "graphics-driver" the indent would be beneficial to indicate how deep in the structure you are. 

Probably I missed something earlier. Do you mean the problem is that it writes the output as a named group? or that it does not have tabs?

Currently it supports multiple tell commands in row, and if called just like --tell it prints all known ones. Since there may be multiple groups of keys I thought having them grouped would be logical to prevent occasional naming conflicts.

> The return code on failure is still 0 for me:

Ok, I am confused. I ran practically same commands as you and get
`
$ ./ags --tell data2
ERROR: Unable to determine game data.
Defined game location is not a valid path.
<...>

$ echo $?
1
`

**Comment by morganwillcock** [comment]
> Currently it supports multiple tell commands in row, and if called just like --tell it prints all known ones. Since there may be multiple groups of keys I thought having them grouped would be logical to prevent occasional naming conflicts.

Yes, I think if grouping things use an indent so you can measure the depth when given any line:
<pre>{
	"config-meta": {
		"gamename": "In Bloom",
		"globalconfig": "./acsetup.cfg"
	},
	"graphics": {
		"driver": "software",
		"screen_width": "1920",
		"screen_height": "1080"
	}
}</pre>

If you just have a flat structure, then don't indent:
<pre>{
"gamename": "In Bloom",
"globalconfig": "./acsetup.cfg",
"graphics_driver": "software",
"screen_width": "1920",
"screen_height": "1080"
}</pre>

I guess there should also be some version number of the actual JSON data too, in-case the format ever needs to change or a value is changed (like graphics driver may return different values or the game gains a GUID).

> Ok, I am confused. I ran practically same commands as you and get

It must be a platform specific problem, if I try on Linux it returns 1, it I try on macOS it returns 0.

**Comment by ivan-mogilko** [comment]
> It must be a platform specific problem, if I try on Linux it returns 1, it I try on macOS it returns 0.

This is out macOS port, maybe its wrapper intercepts the return value?

**Comment by morganwillcock** [comment]
It is just a binary named 'ags', I don't think there is any wrapper around it?

**Comment by ivan-mogilko** [comment]
I mean, in the patched allegro code, it wraps "main" function from ags engine.
Unless there's another wrapper with objective-C code, or is it only used in iOS port?

**Comment by morganwillcock** [comment]
I just cloned https://github.com/ivan-mogilko/ags-refactoring/tree/release-3.5.0--command-tell and built that.

**Comment by ivan-mogilko** [comment]
Yes, but where does allegro library come from?

**Comment by morganwillcock** [comment]
The AGS repo as far as I know:
https://github.com/ivan-mogilko/ags-refactoring/blob/release-3.5.0--command-tell/CMake/FetchAllegro.cmake
I built it with cmake, which downloads and builds the dependencies.

**Comment by ivan-mogilko** [comment]
Perhaps @sonneveld would know more about this, but at a quick glance the return value of Allegro's main is completely ignored when it's called from objective-C wrapper:
https://github.com/adventuregamestudio/lib-allegro/blob/allegro-4.4.3.1-agspatch/src/macosx/main.m#L143

**Comment by ivan-mogilko** [comment]
@morganwillcock 
I remade the branch squashing commits and added json "beautification" (tabs).

**Comment by morganwillcock** [comment]
Reading a little, the call to `NSApp terminate` looks for a delegate `applicationShouldTerminate`. There are examples of this just calling exit:

https://github.com/Shufflepuck/MacAdminQuitApp/blob/e6094de337a88b358a32d6def9d2d04f85a40a7d/MacAdminQuitApp/AppDelegate.swift#L121-L130

Similar response is here:
https://stackoverflow.com/a/2745585
(standard terminate isn't critical and a difference of behaviour for a 'force quit' is deemed problematic)

**Comment by ivan-mogilko** [comment]
I guess macos port should be separate issue, unfortunately I don't have time right now to look into this myself (and I don't own mac to test anything).

> I guess there should also be some version number of the actual JSON data too, in-case the format ever needs to change or a value is changed (like graphics driver may return different values or the game gains a GUID).

Will it be sufficient to output engine version, which may serve as a format reference?

Also, I noticed that in all json examples that you post you keep opening bracket on same line e.g.:
<pre>
        "config-meta": {
		"gamename": "In Bloom",
		"globalconfig": "./acsetup.cfg"
	},
</pre>
Is this a desired format, or not significant?

**Comment by ericoporto** [comment]
Traditionally JSON has the opening bracket on the same line. You can use a [JSON linter](https://jsonlint.com/) to check validity of json outputs. 

```
{
"config-meta": {
		"gamename": "In Bloom",
		"globalconfig": "./acsetup.cfg"
	}
}
```

**Comment by ivan-mogilko** [comment]
I just realize that what I do here is a dirty implementation of a very raw idea.
For instance, there's already a ConfigTree object where engine gathers data for config. It's read and written in INI format, therefore could be reused to write into JSON as well.
Same, there are already names for config options, that could be reused in json of course to match with game config.

**Comment by morganwillcock** [comment]
Outputting in INI format would also be fine and is easier to parse. If it was easier to just dump the ConfigTree object using the INI writer and then also print some extra sections, I think that would be fine too.

**Comment by ivan-mogilko** [comment]
INI has only 1 level of nesting. Can that be a problem?

For example, what if at some point you'd want to have --tell-x command which returns full user config, which also consists of groups and values in them. How do you distinct config from other data then?

**Comment by morganwillcock** [comment]
I think normally you would prefix or postfix the sections, or use a section delimiter to indicate a parent object. This sounds a bad idea but in practice it can work quite well. Here is a good example of how it might be done:

http://orx-project.org/wiki/en/orx/config/syntax

**Comment by ivan-mogilko** [comment]
New pull request: #897

**Pull request closed without merging**
