### PR TITLE
Editor: Script Font and Size selection in Preferences

### PR DESCRIPTION
**Pull request by ericoporto**
Allow selecting which font to use for Script Editor in AGS Editor, and also the font size.

If it's decided we don't want this now, it can be closed. But I thought it was really nice to be able to switch the default font and font size. :)

image

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
I think these new properties should be in "Script Editor" category (currently: "Editor Appearance").

I noticed following bug: the left panel of the script window is not resized when the font changes, until you close and reopen the document. This may cause label numbers not be fully visible.

**Comment by ericoporto** [comment]
Ah, good idea in the Script Editor category!

> I noticed following bug: the left panel of the script window is not resized when the font changes, until you close and reopen the document.

Ah, thanks, I didn't notice before! Will fix!

**Comment by ivan-mogilko** [comment]
I think these new properties should be in "Script Editor" category (currently: "Editor Appearance").

I noticed following bug: the left panel of the script window is not resized when the font changes, until you close and reopen the document. This may cause label numbers not be fully visible.

**Comment by ivan-mogilko** [comment]
Weird, my comment got posted again for some reason... (deleted duplicate)

**Comment by ericoporto** [comment]
Adjusted the mentioned issues!

**Comment by ericoporto** [comment]
Found an issue that could possibly be closed by this , #950

**Comment by ivan-mogilko** [comment]
There's a styling problem with AutoComplete, but it's rather a problem with Scintilla. Unfortunately it does not have a separate style for autocomplete, and also uses some kind of cached "line height" value when displaying autocomplete list. This cached value does not update immediately on setting font and size, but only upon certain changes. This results in list displayed in its own font, but using script editor's line spacing, which increases with the assigned font size.

**Comment by ivan-mogilko** [comment]
On additional note, the tooltip for function parameters is still using fixed font.

**Comment by ericoporto** [comment]
Interesting, I did not notice that. The only way I can think right now without looking more in depth in scintilla code is to remove scintilla autocomplete and use a new one instead. Something like what is here: https://github.com/jacobslusser/ScintillaNET/wiki/Custom-Autocompletion

But before going this route I would look a bit more if it's possible to fix this in some way.

**Comment by ivan-mogilko** [comment]
I wonder if we may use same font for autocomplete for the time being. This way we won't have to rely on hacks.
It looks a little strange, when you set large font in the editor and autocomplete still stays small.

Alternatively, we could try patching Scintilla, add a new Style for autocomplete, in similar fashion to it having its own style for the tooltips. Then add config options for all of these.

**Comment by ivan-mogilko** [comment]
Does this look bad?

autocompletefonts

**Comment by ericoporto** [comment]
The autocomplete looks alright for me but the tooltip I think it benefits from having a different font. Not sure if I am just used to default AGS. I need to check how things are VS and other IDEs - I am drawing a blank trying to remember, but I am not on my computer right now.

**Comment by ivan-mogilko** [comment]
Well, tooltip has its own style, so it may be kept, and perhaps configured in preferences.

**Pull request merged**
