### PR TITLE
Engine: report extra mem info on OoM failure

### PR DESCRIPTION
**Pull request by ericoporto**
The error message for Out of Memory would look like this:

image

Here is a demo game that causes an OoM error: [OoMTest.zip](https://github.com/adventuregamestudio/ags/files/13691155/OoMTest.zip)

- https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-memorystatusex
- https://learn.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getprocessmemoryinfo

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
@ericoporto almost 1.5 GB of extended sprite memory, this means either memory is filled by dynamic sprites, or spritecache is not working right.

**Comment by ivan-mogilko** [comment]
To double check, I think the quit message should also be printed to the log, correct?

**Comment by ericoporto** [comment]
Ohh, right, I forgot about the log. Yeah, that would be a good idea.

**Comment by ivan-mogilko** [comment]
I had a false memory that it's done in quit function, but I cannot find it there.

**Comment by ivan-mogilko** [comment]
Actually, first thing to do should be to bring DisplayAlert function to consistency. Right now different platforms do 3 things in various combinations there:
- Some display message box using system api or SDL,
- Some print into stdout or stderr depending on a `_logToStdErr` setting,
- Some print to log. (Also, I realized that printing to log uses wrong message type, it should use Alert, but uses Warn)

This all has to be brought to a uniform rule IMO.

**Comment by ericoporto** [comment]
I think Windows default of displaying a message box unless `--no-message-box` is passed is a good default.

I just am not super sure of Windows in particular using the SDL version of the function because the version it does has been working fine and I worry about switching to that this late in beta.

**Comment by ericoporto** [comment]
Otoh, maybe using SDL in Windows can fix #1034, although I forgot how to reproduce that to check if it's still a problem.

**Comment by ivan-mogilko** [comment]
If using SDL's message box on Windows is a concern, then platform driver could have a virtual MessageBox method, overriding it.

**Pull request merged**
