### PR TITLE
Fix for scaling issues on iOS

### PR DESCRIPTION
**Pull request by jonreyno**
Adapted these changes from Janet's iOS branch. Without them, the default scale is off which causes graphical artifacts and improper upscaling.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
@jonreyno your first commit contains way too numerous changes, many of which seem to be completely unrelated to the topic of this PR. Could you please filter these out?

If you believe these are still necessary, they may be suggested as another PR. Alternatively, change this PR's title and add thorough explanation of what is changed and why. Multiple unrelated changes should also be done as separate commits.

I'd like to note, just in case, that release-3.5.0 branch is for critical fixes only, and if there's more serious code changes necessary (as well as refactoring, cleanup, etc), they should go into the master instead, where we may prepare an 3.5.1 update (for example, 3.4.0 was released with broken Android port, which was restored as a part of 3.4.1).

**Comment by ivan-mogilko** [comment]
@sonneveld I don't know if you have any pending changes to iOS, but if I remember correctly you were working on it in the past? If so, could you also take a look to see if iOS specific changes conflict with anything?

**Comment by jonreyno** [comment]
Sorry! I’m new to pull requests (this is my first). That extra changelist was a mistake... didn’t mean to commit everything like that. I also didn’t intend those to be part of the pull request? Guess I don’t fully understand how that works. I thought it was just for the differences that existed when I opened the pull request rather than for all future differences as well. I’ll revert those other changes and put them in one by one as I had intended. Is there a way to just have the pull request be for certain files as I had intended?

**Comment by ivan-mogilko** [comment]
>  I thought it was just for the differences that existed when I opened the pull request rather than for all future differences as well.

Sorry, I don't understand what you meant by this :).

When you are merging branch A into another branch B (and this is what pull request is about), git compares commits (changesets) in both branches, and tries to apply commits from branch A, that do not exist in branch B.

> Is there a way to just have the pull request be for certain files as I had intended?

For that you'd need to create a new branch, and make commit(s) in it, only including necessary files or distinct changes.

**Comment by rofl0r** [comment]
hint: use `git add --patch`, if you can (i.e. linux terminal user)

**Comment by jonreyno** [comment]
@ivan-mogilko 

> PS. It's best to create new branch at the topmost commit of _our_ branch, this means that yours will be like a continuation of ours. That works best usually.

By this do you mean create a branch in your repo or create a branch at the top level (master) of my fork? And is the master branch just for Ags 3 or is it also for Ags 4?

**Comment by ivan-mogilko** [comment]
> By this do you mean create a branch in your repo or create a branch at the top level (master) of my fork?

Create a branch in *your* repo, at the commit that corresponds to our topmost commit in our branch.

I.e., if you prefer to PR against our release-3.5.0, then find _our_ last commit in *your* clone of release-3.5.0 and branch off there.
If you prefer to PR against our master, then, similarily, find our last commit in your clone of master.

> And is the master branch just for Ags 3 or is it also for Ags 4?

Master currently corresponds to ags3 development. We are expecting to have at least couple of releases there, which should include switching to SDL backend.
The story of ags4 is bit complicated. So far everything that went into ags3 was also merged into ags4 (except backward compatibility and stripped features). _Supposedly_ we will continue doing so in the nearest future.
There's a developers' discussion going on backstage regarding future development there, but right now I cannot tell anything particular.

**Comment by ivan-mogilko** [comment]
Looking at your repository, your release-3.5.0 branch is bit outdated, corresponding to 3.5.0.20 build, while the latest build in our release-3.5.0 branch is 3.5.0.22.

If you have all those ios changes saved somewhere else, what you could do is:
* reset your release-3.5.0 branch to the last of our commits in your repo.
* do git pull to sync release-3.5.0 branch with ours.
* create a branch for PR, e.g. called "3.5.0-ios-fixes" (or whichever you like)
* add necessary commits in this branch.
* create a PR.

On the other hand, seeing as your changes are mostly in the iOS files, you could as well just do hard reset to remove 3 commits, then reapply only changes you need, and force-push your branch again. That would automatically update this PR.


In case of the master branch it's more complicated. We switched "master" head from ags4 to ags3 recently, so to update properly you would have to first "fetch remote" to get where our new master is, then hard reset your master to the location of our master, and force push this new master to your remote repo.
(again making sure that you have your changes save somewhere else)

**Comment by jonreyno** [comment]
@ivan-mogilko After a bit of learning how git works I managed to get my master in line with yours so I will reopen the request from there. Thanks for the help!

**Pull request closed without merging**
