### PR TITLE
Update sound config to 3.6.0

### LINKED ISSUE #1565: Adjust Sound Config for SDL2 AGS
The Sound and MIDI configuration in AGS in Config Tree, and the interfaces (command line, acsetup.cfg, and WinSetup) currently expects the behavior from the previous allegro4 based AGS. 

We need to either 
- remove these configurations and rely in the automatic behavior from SDL2 or 
- update the configuration so it can modify what SDL2 uses.

**Additional info**

Retrieving the list of available audio drivers can be achieved by using `SDL_GetNumAudioDrivers()` and `SDL_GetAudioDriver(int i)`, at runtime.

Setting the audio driver can be done through  `SDL_setenv("SDL_AUDIODRIVER", "directsound", 1);` to specify a specific audio driver. Since SDL2 2.0.16 it's possible to also pass a list of comma separated values (ordered) so that if the device fails the list is used to provide fallback options. 

Alternatively, using `SDL_AudioInit(driver_name)` can directly specify the driver name.

---

Currently it's possible to influence AGS through OS environment variable `SDL_AUDIODRIVER`, similar to `SDL_setenv`, following https://wiki.libsdl.org/FAQUsingSDL#how_do_i_choose_a_specific_audio_driver

---

Interfaces must also be adjusted:

- [ ] Adjust acsetup.cfg documentation in OPTIONS.md
- [ ] Adjust Command Line parameters
- [ ] Adjust WinSetup

### PR DESCRIPTION
**Pull request by ivan-mogilko**
Resolves #1565, #1566

Implemented config options:
```
[sound]
enabled = [1,0]
driver = id
```

"driver" value is system specific; empty value means use defaults.

Removed config option for threaded audio.

Updated winsetup, and Editor's Default Setup pane.

### CODE REVIEW

**Comment by ericoporto** [comment]
This works, and the winsetup has the options removed. I noticed the tell command still mentions `midiid` and `digiid`:

```
.\audio_test.exe --console-attach --tell-config
...
[config@sound]
digiid = -1
driver =
enabled = 1
midiid = -1
threaded = 0
usespeech = 1
```

**Comment by ivan-mogilko** [comment]
--tell-config prints everything found in config files.

**Comment by ericoporto** [comment]
ah, that's correct! Very curious, I rebuilt the game but it still had the removed options in the acsetup.cfg file, once I manually removed them with notepad from the file they were going forever and did not appear in any tell flag.

**Comment by ivan-mogilko** [comment]
Changed to delete the config file before writing.

**Comment by ivan-mogilko** [comment]
Ah! i forgot to update the readme, will to that separately.

**Pull request merged**
