### PR TITLE
Fixed C# project module "AGS.Types" so that it successfully builds in xBuild on *nix systems

### PR DESCRIPTION
**Pull request by persn**
Like the title says, I have more details on the individual commit messages so make sure to read those.

### CODE REVIEW

**Comment by sonneveld** [comment]
Thanks for this and other pull requests.. I'll have to get the build server working again before I can accept them though.

**Comment by persn** [comment]
No rush.. I'm still experimenting with the other C# modules.

**Comment by ivan-mogilko** [comment]
Regarding EntryPointOffset which references otherwise unused _entryPointOffset.
Comment there sais:
> Pre-3.1.1 wrote this into the Game.agf XML, so we have to keep this dummy property to allow it to deserialise.

This is a caveat of AGS project serialization system, which I do not really like. Something could be done with it later, but for now you could remove this property if you add following attribute to the DialogOption class:

<pre>[DeserializeIgnore("EntryPointOffset")]</pre>

That's an attribute I created while ago for the purpose of deprecating properties without breaking deserialization.

**Comment by persn** [comment]
Updated according to feedback

**Pull request merged**
