### PR TITLE
Script API: implemented Game.IgnoreUserInputForNextTextMs

### PR DESCRIPTION
**Pull request by ivan-mogilko**
By user request, this implements Game.IgnoreUserInputForNextTextMs, as a complement to existing Game.IgnoreUserInputAfterTextMs.

( Definitely, I am aware that these names are ugly :) )

The point of the existing property (Game.IgnoreUserInputAfterTextMs) was to help with misclicks when skipping character speech. When speech is also skipped automatically (by a timer), player may click too late, before realizing that speech was already changed to the next line, or final line ended. In this case player's click would skip next line before player is able to read it, or perform some other action. To counter this, the feature would block user's input for a limited amount of time after auto-skipping the text.

A new user request was to be able to restrict input blocking to only the case when there's next line of text. Because it's impossible to know if there's one at the time when the previous ends, following function is implemented:
* when the text is skipped automatically, it schedules an input block and starts a timeout, but does not disable input just yet.
* if a new line of text will be displayed during this timeout, then the scheduled input block is activated for the remainer of this timeout.
* if user input was already disabled by the first property (Game.IgnoreUserInputAfterTextMs), then the timeout that lasts longer is chosen.

This way a game dev may set up separate timeouts for disabling user input after any text line, and disabling it only if there's a new text line right afterwards.

Additionally, this PR fixes inconsistent handling of few "service" input commands, and cutscene skipping (because input is still handled separately in various game states in the engine code). By the rule, the cutscene should be always skippable, even if player's input is otherwise blocked.

### CODE REVIEW

**Comment by messengerbag** [comment]
I'm still sort of confused about why this approach is necessary.

Instead of all this, wouldn't it make more sense to just alter the logic that allows a user to skip a line (i.e., takes the user input and causes the dialog to advance under certain conditions), so that it simply checks whether the timeout is active before triggering the skip? That should automatically ensure that there aren't any side effects (blocking players from skipping cutscenes, etc.), right?

I would also cancel the timeout when it blocks a click/keypress skip, so that it only ever blocks the first one.

**Comment by ivan-mogilko** [comment]
> Instead of all this, wouldn't it make more sense to just alter the logic that allows a user to skip a line (i.e., takes the user input and causes the dialog to advance under certain conditions), so that it simply checks whether the timeout is active before triggering the skip? That should automatically ensure that there aren't any side effects (blocking players from skipping cutscenes, etc.), right?

This is what the new property is doing, unless I misunderstand what are you refering to.

> I would also cancel the timeout when it blocks a click/keypress skip, so that it only ever blocks the first one.

It cancels the timeout if there's a click while there's no new text on screen. I could make it cancel it always.

**Comment by ivan-mogilko** [comment]
I am currently investigating whether it's possible to implement wanted behavior in script using BlockingTextIndex property (#1053).

**Comment by ivan-mogilko** [comment]
Cancelled, since #1053 seem to be enough for now.

**Pull request closed without merging**
