### PR TITLE
Windows Installer build scripts.

### PR DESCRIPTION
**Pull request by sonneveld**
These are not perfect but hopefully enough to start getting an installer building through teamcity. Comments welcome.

### CODE REVIEW

**Comment by sonneveld** [comment]
Oh TeamCity won't include the manual until I add those artifacts, but that requires the user manual pull request to go in.  I think both pull requests can go in at the same time.. the installers just won't have the help file in the first couple of builds.

**Comment by sonneveld** [comment]
Yay, okay, now this one works in Teamcity and the user manual one fails (specifically the installer job).  Anyway, they should both be okay to merge in.

**Comment by ivan-mogilko** [comment]
I tried to run this script on my PC and I found following:
* I got syntax error in build.py at "except Exception**,** e". I learnt that modern Python requires "Exception **as** e" syntax. Which version of python should be used to run the script?
* This script requires pywin32 module.

May the requirements be mentioned somewhere?

**Comment by ivan-mogilko** [comment]
Since this is Windows installer anyway, I learnt there is a way to make it choose python version explicitly by using python launcher: https://docs.python.org/3/using/windows.html#python-launcher-for-windows.

Will this method be suitable for our case?

**Comment by sonneveld** [comment]
Actually you raise a good point. I'm used to just writing all my python code for python2.  The version I use (and is installed on build server) is activepython 2.7 from http://www.activestate.com/activepython/downloads . It includes pywin32 by default.  The py launcher doesn't seem to come with python2 , at least not the version I have installed.

I'm happy to fix so it works in python3 instead.

**Comment by sonneveld** [comment]
As of commit 9819a8d, there is a README with the minimum windows build requirements.

**Comment by sonneveld** [comment]
Ah hangon, I've just realised other ports have their own README. I'll move my additions into a Windows README

**Comment by sonneveld** [comment]
Issue: vcredist_x86.exe isn't installed into tmp.

**Comment by sonneveld** [comment]
Ensure correct version of vcredist is installed. (changed teamcity config to download right one) In 436f9b6

**Comment by sonneveld** [comment]
Tested current build. After uninstalling the VS2008 redist, it will detect it isn't installed and give you an option to install it.  Reinstalling again, it will not show the option.

**Pull request merged**
