### PR TITLE
Enable Travis-CI builds for the ags3 branch

### PR DESCRIPTION
**Pull request by morganwillcock**
This file needs to be present in the branch in order to build it. For release purposes it probably needs to use the chroot build script or also run a build in a 32 bit container, and there is the Allegro version to consider, but for the moment just checking that builds occur is a good start.

Edit: the current build error should be covered by #717

### CODE REVIEW

**Comment by morganwillcock** [comment]
Next error:
<pre>Linking engine...
/usr/bin/ld: unrecognized option '--push-state'</pre>
I guess this is related to recent changes for compiler requirements or something has introduced an option; the master branch has previously built without the same issue.
<pre>$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4</pre>

**Comment by ivan-mogilko** [comment]
Could you find the commit when this error appears? Assuming it was building with -std=c++11 CXXFLAGS then most recent changes suppose to not affect building on gcc at all.

What is "--push-state" related to?

**Comment by sonneveld** [comment]
I had some issues linking static and dynamic libraries. I was using push pop state to temporarily change settings for linking a particular library without affecting later ones (which could include system libs)

**Comment by morganwillcock** [comment]
> Could you find the commit when this error appears?

I believe it is 4166c65

**Comment by morganwillcock** [comment]
It seems the older linker just doesn't support that flag, and the commit adds the flag. Maybe that is worthy of being raised a separate issue, but it might not have any real world impact. Probably something for someone else to decide...

I'll update this PR to use the chroots instead, which should let it build successfully.

**Pull request merged**
