### PR TITLE
Adds MacOS build instructions for using CMake with Xcode and changes CMakeLists.txt to use game.ags 

### PR DESCRIPTION
**Pull request by ericoporto**
This PR adds MacOS (OSX) build instructions for using CMake with Xcode.
It also renames `ac2game.dat` to `game.ags` in the context of MacOS (OSX) build and the game initialization script.

### CODE REVIEW

**Comment by morganwillcock** [comment]
Could the instructions page have the `CMake` + `make` instructions too?
```
export BUILD_TYPE=release
mkdir build_$BUILD_TYPE
cd build_$BUILD_TYPE
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
make
```

**Comment by ericoporto** [comment]
Sure. I can also explain how the `.app` directory works and `info.plist` from the perspective of the app that is built with this.

**Comment by ericoporto** [comment]
@morganwillcock I added the mentioned instructions

**Comment by morganwillcock** [comment]
OK, I'm still a little worred about the signing process if it just signs the engine and the data file is just copied into place (either manually or with a hook). I'll try out the instructions and see how it compares to the existing XCode projects that I think I still have.

**Comment by ivan-mogilko** [comment]
Is this okay to merge?

**Comment by ericoporto** [comment]
@morganwillcock are you cool with merging this?

**Comment by morganwillcock** [comment]
I would still like to check the XCode project first to double check what gets signed, maybe I can do it at the weekend.

**Comment by morganwillcock** [comment]
It doesn't seem to work when I've tried, unless I've misunderstood a step or maybe the file copy doesn't apply when generating an Xcode project? I made a release build and the game isn't in there, but the previous 0 byte file with the old name is. I copied game.ags into OSX/Resources before I did anything with CMake or Xcode.

<pre>
$ find OSX/Resources -name "*.ags"
OSX/Resources/game.ags
$ find buildXcode/Release/AGS.app -name "*.ags"
$ find buildXcode/Release/AGS.app
buildXcode/Release/AGS.app
buildXcode/Release/AGS.app/Contents
buildXcode/Release/AGS.app/Contents/MacOS
buildXcode/Release/AGS.app/Contents/MacOS/AGS
buildXcode/Release/AGS.app/Contents/Resources
buildXcode/Release/AGS.app/Contents/Resources/speech.vox
buildXcode/Release/AGS.app/Contents/Resources/audio.vox
buildXcode/Release/AGS.app/Contents/Resources/ac2game.dat
buildXcode/Release/AGS.app/Contents/Resources/acsetup.cfg
buildXcode/Release/AGS.app/Contents/Resources/ags.icns
buildXcode/Release/AGS.app/Contents/Info.plist
buildXcode/Release/AGS.app/Contents/PkgInfo
</pre>

**Comment by ericoporto** [comment]
I changed the title to make clear it requires the code in the branch for the instructions to make sense.

**Comment by morganwillcock** [comment]
In both cases (static Xcode project in ags-osx-nick branch, and this one created with CMake) the data is separate from the engine when built, but if you check the `_CodeSignature/CodeResources` file the game's data file is listed with a hash value. I haven't been able to find a way to enforce the integrity of that though. Maybe it would be enforced automatically if I paid Apple a yearly developer fee.

So the instructions seem OK to follow, but I would still be worried that signing the binary might lead to someone using that binary for malicious purposes and then the person who signed it might get their developer account or AppleID revoked. It is fairly trivial to see who signed it if you rely on the free developer account, since it is likely going to be the e-mail address associated with the AppleID:

```
codesign -dvv buildXcode/Release/AGS.app 2>&1 | grep "^Authority=Mac Developer:"
```

Perhaps it is better to either remove the signing instructions so we take no responsibility for what people do with the signing step, or add a warning that signing the project needs some thought and care, or do both.

**Comment by ericoporto** [comment]
Do you know how people sign things using binary/proprietary things in MacOS?

I found a page here -> https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/

But it talks about codesigning. There must be a way to sign something that includes binaries, like a proprietary GUI library or some other library. 

I will for now just remove mentions of the sign process since it's unclear for me too.

**Comment by ericoporto** [comment]
If it's ok as this, I can squash the last two commits that modifies the README and force push.

**Comment by morganwillcock** [comment]
> Do you know how people sign things using binary/proprietary things in MacOS?

I tried adding the resource files as separate copy tasks and checked the 'code-signing' box for the data file (so I think code-signing is meant to also incorporate checks on data files too) but it didn't make a difference. I guess we need to ask an expert, but without paying Apple I think any app bundle that is built is meant to be for testing purposes only, so I wouldn't be surprised if the code-signing validation is just skipped for the user who has signed it. But as well as the issue of signing, there is also the issue that a standalone engine with separate data file is probably not allowed to enter the macOS AppStore.

> If it's OK as this, I can squash the last two commits that modifies the README and force push.

The other parts are OK, I think.

**Comment by ericoporto** [comment]
I squashed the last commits so it's one for the CMake + alplmac.mm and other for the additional instructions.

**Comment by ericoporto** [comment]
@morganwillcock look at what I found here: http://www.edenwaith.com/blog/index.php?p=112 , here's a backup in case this goes down 
[porting-ags-games-to-mac.zip](https://github.com/adventuregamestudio/ags/files/4855239/porting-ags-games-to-mac.zip)

**Comment by edenwaith** [comment]
As I mentioned in my blog post, a proper certificate is needed (which I always get from the Apple Developer portal) to properly code sign an app.  This should be the last step of the process after the app bundle has been constructed.

**Pull request merged**
