### PR TITLE
Dev 3.4.0  tidy font

### PR DESCRIPTION
**Pull request by jclee**
Just trying to tidy up some code in the font renderers:

* Eliminate some globals
* Limit some globals to static scope

### CODE REVIEW

**Comment by sonneveld** [comment]
Weird, for some reason, none of the scripts are executable. Does github show when file execute bits are changed?

**Comment by ivan-mogilko** [comment]
Well, we will have to check and fix port building in 3.4.0 anyway, when we will be preparing beta release.

**Comment by ivan-mogilko** [comment]
@jclee , the pull request seem good to me in general, except for the few cases of mismatching code formatting (sometimes you changed one in the pre-existing code, and also some of your new code have varied formatting).

In the convention we use, we put asteriks/ampersand (pointer/reference symbol) beside the name, rather than the type.
(The old AGS code which is still kept unchanged is a mess in regards to formatting, but when writing new code we apply the one we decided to use.)

We have a coding convention draft link posted on AGS forums, which is probably not the most obvious place for people who come to the project from github; and that's my oversight that it is still not added to our repository readme:
http://www.adventuregamestudio.co.uk/wiki/AGS_Engine_Coding_Conventions

I will also add couple of comments to the commits themselves; there are couple of minor things I would like to see changed, and one optional one.

**Comment by ivan-mogilko** [comment]
This is probably not a "correct" thing to do, but it's been more than a month and @jclee did not answer anything; the proposed changes may be useful, so I decided to merge it and fix the few remaining problems myself.

**Pull request merged**
