### PR TITLE
multifilelib: don't allow head sig search to extend past tail offset

### PR DESCRIPTION
**Pull request by sonneveld**
This fixes issues on systems where it is an error to read at an offset past end. (reading at end should still give you 0 bytes though)

edit: I didn't add a check to Seek itself since it would require grabbing the file size on load. Plus, we can't always rely on that if we're reading sub-resources (in instances where we pass Streams already repositioned to the right resource).

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
I find this quite disturbing, there are multiple Seeks in the program, do we need to check them all for this potential problem? Other people may later add/change the code without being aware of this issue too.
I *would* actually consider to control this inside the stream somehow.

Regarding this commit -

Could you, please, fix the coding style?

A bit of nitpicking:
* There's `in->Seek(-(soff_t)TailSig.GetLength(), kSeekEnd);` right above your added code, may be possible to avoid doing seek twice and remember offset after first one.
* Perhaps condition should be `abs_offset < (tail_abs_offset - HeadSig.GetLength())`?

**Comment by sonneveld** [comment]
> Frankly, I find this quite disturbing, there are multiple Seeks in the program, do we need to check them all for this potential problem? What kind of error happens if we read past Seek, does it breaks further reading attempts?

I think it depends. In this instance we're reading unknown data and then doing an absolute seek on it. We should absolutely check this value before passing it to Seek. While we could also check in Seek, it would mean that we're hiding bad behaviour.

On some platforms, reading past the end of the file raises an error and aborts the program. I don't know if this is posix compliant, but that's what happens. Note, reading *at* the end of the file is fine. (you just get 0 bytes back)

> Perhaps condition should be abs_offset < (tail_abs_offset - HeadSig.GetLength())

I figured just checking against `tail_abs_offset` was fine because that's at least as long as HeadSig but I guess no harm adding it in.

**Comment by sonneveld** [comment]
Ok I made those fixes and then attempted to fix the coding style. I split ReadSigsAndVersion into ReadSigs and ReadVersion since they do different things. That allowed me to refactor ReadSigs to be flat via early returns.

**Comment by ivan-mogilko** [comment]
Excuse me, but why is your commit called "fix the coding style" while it does something different?

Also... the code style is not correct in the latest commit again.

**Comment by sonneveld** [comment]
> Excuse me, but why is your commit called "fix the coding style" while it does something different?

I didn't think there was a style violation so I thought maybe you wanted a general code tidy up?

With coding style, are you referring to the brace on a new line? That's the only thing I could see after looking again.

**Comment by ivan-mogilko** [comment]
> With coding style, are you referring to the brace on a new line?

Yes, I meant braces, nothing else. I just that your commits changed the code style in otherwise consistent file.

**Comment by sonneveld** [comment]
> Yes, I meant braces, nothing else. I just that your commits changed the code style in otherwise consistent file.

ahhh ok. fixed. I was comparing variable name styles and thinking I was going crazy.

**Comment by sonneveld** [comment]
> Refactor is ok if you think it makes things more clear.

I believe it does but I'll won't add it to `release-3.5.0`. I thought maybe that's what you were suggesting :)

**Comment by rofl0r** [comment]
> On some platforms, reading past the end of the file raises an error and aborts the program. I don't know if this is posix compliant, but that's what happens.

nope, that's not compliant at all. on which platform did you encounter this broken behaviour?

**Comment by sonneveld** [comment]
> nope, that's not compliant at all. on which platform did you encounter this broken behaviour?

Can't really say. It's more of a posix compatiblity layer though.

**Comment by ivan-mogilko** [comment]
I'll take a guess this is one of the console systems people began porting AGS to recently (but cannot talk about because of legal conditions or something).

**Pull request merged**
